### ISSUE TITLE
Mouse prevented from moving to second monitor across tab bar

### ISSUE THREAD

**Issue by phipolis** [mlutfy/hidetopbar#100]
When I add a second monitor and arrange it to be above the primary display, the mouse can pass over the menu bar to the second display and back. If I enable hidetopbar with "show panel when mouse approaches edge of the screen" on, the mouse can no longer pass between the two screens. Turning off "show panel when mouse approaches edge..." allows the expected behavior to resume. 

Gnome 3.18.5

**Comment by tuxor1337** [comment]
That's more or less intended, i.e.: We simply don't support the case where your second monitor is above the primary display - and you still want to show the panel when the mouse approaches the edge of the screen.
