### ISSUE TITLE
add support for GNOME 3.20

### ISSUE THREAD

**Issue by edge** [mlutfy/hidetopbar#101]
First, thanks for the plugin. It's probably one of the most useful plugins I have.

I'm on rolling Arch, so it'd be cool if hidetopbar could support GNOME 3.20. It worked when I was on 3.18, so it shouldn't be too much of a change.

**Comment by tuxor1337** [comment]
GNOME 3.20 is already supported: #95. That's also the case for the latest version from extensions.gnome.org.

**Comment by edge** [comment]
Ah, my bad. Sorry for the trouble.
