### ISSUE TITLE
Flood of warnings in the log files

### ISSUE THREAD

**Issue by jsherman0018** [mlutfy/hidetopbar#102]
This stopped the flood of warnings in the log files:

    Gjs-WARNING **: JS ERROR: TypeError: Shell.ActionMode is undefined

On line 112 in ~/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/intellihide.js:

                    if (Shell && Shell.ActionMode && Main.actionMode != Shell.ActionMode.NORMAL)
                        return false;

**Comment by tuxor1337** [comment]
Which version of gnome and which OS are you using? Furthermore, are there any other extensions you are using in parallel?

**Comment by tuxor1337** [comment]
This error only occurs in Gnome 3.14 because there it was `Shell.KeyBindingMode.NORMAL` instead of `Shell.ActionMode.NORMAL`. Since we dropped support for 3.14, we can close this.
