### ISSUE TITLE
It hides window titlebar sometimes

### ISSUE THREAD

**Issue by umpirsky** [mlutfy/hidetopbar#103]
Still not sure how to reproduce it, but sometimes (maybe after waking from sleep) it hides windows titlebar. For all windows.

Can be restored after going full screen and back.

Ubuntu 16.04, Gnome 3.18.

**Comment by tuxor1337** [comment]
Do you really mean that window titlebars are hidden or do you mean that the top bar overlaps the titlebar of (maximized) windows?

This bug definitely needs more details on the setup (other extensions, current hidetopbar-settings) and step-by-step instructions on how to reproduce.

**Comment by umpirsky** [comment]
Probably top bar overlaps the titlebar of (maximized) windows. It's hard to tell and reproduce, it use to happen pretty random. I don't use it any more so cannot give more information unfortunately. Thanks.

**Comment by tuxor1337** [comment]
Okay, I'm closing this for now. If somebody else runs into this problem, feel free to reopen adding the requested information.
