### ISSUE TITLE
Need to be updated for Gnome 3.21.91

### ISSUE THREAD

**Issue by Chris00** [mlutfy/hidetopbar#107]
This extension does not work with Gnome 3.21.91.

**Comment by tuxor1337** [comment]
I don't run Gnome 3.21, but you can help getting this extension to 3.21: Edit your metadata.json to include the version string "3.21" (in line 2) and report back whether the extension works. If it doesn't work, report back what issues you have, if there are error messages or anything else that might help analysing the problem.

**Comment by Chris00** [comment]
On 2016-09-10, tuxor1337 wrote:
> 
> I don't run Gnome 3.21, but you can help getting this extension to 
> 3.21: Edit
> your metadata.json to include the version string "3.21" (in line 2)

I did that and followed the installation instructions of 
https://github.com/mlutfy/hidetopbar with no error but, in the gnome 
tweak tool, it is said that the extension does not support the shell 
version.  What am I missing?

**Comment by zapashcanon** [comment]
@Chris00, how did you install the extension before ? If it was using your distribution's package manager, there may some some conflict as it won't be installed in the same place.

**Comment by Chris00** [comment]
On 2016-09-11, Léo Andrès wrote:
>
> @Chris00, how did you install the extension before ? If it was using 
> your distribution's package manager, there may some some conflict as 
> it won't be installed in the same place.

I installed it before through the website (there is no "hidetopbar" in 
/usr/share/gnome-shell/extensions/).  hidetopbar@mathieu.bidon.ca  is 
the only extension in ~/.local/share/gnome-shell/extensions/

**Comment by Chris00** [comment]
It turns out that I had to use the full `3.21.91` as the shell number, `3.21` was not meaning "any 3.21.* version".  It seems to work fine.

**Comment by coldtobi** [comment]
There is some input form the Debian Gnome maintainers as well:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=837594

"In the past, it was necessary to explicitly declare supported
gnome-shell versions in metadata.json. This was lifted in gnome-shell
3.21.92 [1].

"Nowadays, the user interface has mostly stabilized with most changes
happening under the hood. As a result, extensions written for
previous versions of GNOME Shell are very much expected to keep
working on updates, if it wasn't for the version check that requires
a version bump in the extension metadata. There has been a setting to
disable that check for a while, but it's existence isn't widely known
(hence the common perception that "everything breaks on updates").
While there is still some risk that an out-of-date extension can be
enabled without error, but fails spectacularly later (where we cannot
catch the exception), it is reasonably small by now when compared to
the ~95% of extensions that can be "unbroken", so swap the default
value to disable version checks by default."

Regards, Michael

[1] https://git.gnome.org/browse/gnome-shell/commit/?id=5e0e3e
'

**Comment by coldtobi** [comment]
I've just verified: The extension seem still to work with gnome-shell 3.21.91dpkg -l gnome-shell:

```
# dpkg -l gnome-shell
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                   Version          Architecture     Description
+++-======================-================-================-=================================================
ii  gnome-shell            3.21.91-2        amd64            graphical shell for the GNOME desktop

```

**Comment by tuxor1337** [comment]
I'm glad it's working for you. However, I don't think it's a good idea to add "official" support for unstable GNOME versions (those with odd version numbering: 3.17, 3.19, 3.21, ...). Therefore, I'm not going to add 3.21.91 to metadata.json.

@coldtobi Nice to know they permanently activated that feature at last.
