### ISSUE TITLE
Top bar doesn't go away when I'm with multiple monitors and change focus between workspaces

### ISSUE THREAD

**Issue by joadr** [mlutfy/hidetopbar#110]
When I'm with 2 monitors, If I'm working in a the seccond monitor then go back to the first, and focus the first... for example google chrome, the top bar doesn't go away I have to press super button twice to make it dissapear and it's very annoying.

**Comment by tuxor1337** [comment]
I don't understand what this is about. Please give clear step-by-step instructions on how to reproduce. Forthermore, I need more information about your setup (gnome version, other extensions, hidetopbar-settings).
