### ISSUE TITLE
HotCorner is null in multi-monitor setups

### ISSUE THREAD

**Issue by nobol** [mlutfy/hidetopbar#113]
OS: Arch Linux
Gnome Version: 3.22

Sometimes, when I log into my PC, the extension crashes (since the 3.22 update) and Looking Glass tells me this: `HotCorner is null`. I have no clue why (loaded asynchronously?), but I could fix it in the panbelVisibilityManager.js, by updating the [_updateHotCorner function](https://github.com/mlutfy/hidetopbar/blob/master/panelVisibilityManager.js#L255) like this:

```
_updateHotCorner: function(panel_hidden) {
        let HotCorner = Main.layoutManager.hotCorners[0];

        if (HotCorner) {
          if(!panel_hidden || this._settings.get_boolean('hot-corner')) {
              HotCorner.setBarrierSize(PanelBox.height);
          } else {
              Mainloop.timeout_add(100, function () {
                  HotCorner.setBarrierSize(0)
              });
          }
        }
    },
```

So I simply check if `HotCorner` exists. Not that fancy, I know, but at least it works. Maybe you could consider releasing a version with this patch. 

And Thank you for 1. getting me into extension debugging and 2. this awesome extension!

**Comment by tuxor1337** [comment]
Hm, it's not clear to me that the proposed fix won't have any side effects. We need more feedback from other users about this before we can release this patch.

**Comment by nobol** [comment]
Okidoki, then I will try to give you as much information as I can:

1. I'm  on wayland (I think it is default since 3.22?)

2. when I open looking glass and type `JSON.stringify(Main.layoutManager.hotCorners[0])` into the elevator it returns `null`. Still the HotCorner is working as expected :/ 

I suspect that the Main.layoutManager.hotCorners array holds two elements, my notebook's and my monitor's screen. As my monitor does not have a hotCorner, the value hotCorners[0] equals null, while hotCorners[1] equals my notebook screen! I'm going to play around with the code and tell you more.

**Comment by AlexWayfer** [comment]
I also have Arch Linux with Gnome 3.22, can't install this extension at all.

I don't know why, but I think that the problem may be in this.

**Comment by TiagoDanin** [comment]
![image](https://cloud.githubusercontent.com/assets/5731176/19603087/3525ca20-9786-11e6-9bb5-8bf5a4b6af1c.png)

Worked in Gnome 3.22.1

**Comment by tuxor1337** [comment]
Is this still an issue? I'm also on Gnome 3.22 using Wayland and my setup doesn't show the behaviour described above.

**Comment by nobol** [comment]
@tuxor1337 I just tried to reinstall the extension, still the same error occurs:

![screenshot from 2016-11-29 17-31-27](https://cloud.githubusercontent.com/assets/7189919/20718779/2368aba2-b65a-11e6-9ab7-97f69fbf2158.png)

Also looking glass shows the same error `HotCorner is null`.

And I am also on a fresh Arch Linux install , with Gnome 3.22 and Wayland :/

**Comment by tuxor1337** [comment]
Does this issue only apply to multi-monitor setups?

**Comment by nobol** [comment]
@tuxor1337 you are a freaking genius! That's it, while installing, only one display can be used!

**Comment by tuxor1337** [comment]
Okay, then I will have to wait until I have a multi-monitor setup to track this issue down.

**Comment by rhabbachi** [comment]
Facing this same issue after Upgrading to Gnome 3.24. Makes the extension unusable.

@tuxor1337 Any updates on this?

I'm very thankful for all your efforts. I use this extension on all of my setups!

**Comment by MageParts** [comment]
I had the same issue on Zesty (17.04), gnome-shell 3.24. Installation worked properly with only one monitor attached, but when reattaching my second monitor I got the samme issue again. 

The if statement provided by @nobol really helped though, thanks :-)

**Comment by rhabbachi** [comment]
@MageParts Agree that the change @nobol proposed worked around the issue.
