### ISSUE TITLE
Error message in gnome-shell 3.14.4 (CentOS7.2) after recent update.

### ISSUE THREAD

**Issue by gnarendran** [mlutfy/hidetopbar#116]
gnome-session: (gnome-shell:2290): Gjs-WARNING **: JS ERROR: TypeError: Shell.ActionMode is undefined
gnome-session: intellihide<._init/<@~/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/intellihide.js:112

**Comment by gnarendran** [comment]
So intellihide.js should also do as panelVisibilityManager.js does, which is to define and use const ShellActionMode similarly.

**Comment by tuxor1337** [comment]
3.14 is no longer supported, sorry.

**Comment by gnarendran** [comment]
Ok fine. But the metadata.js says otherwise (which I assume caused the extension to be updated). 
 Regards,Narendran Gopalakrishnan. 

    On Wednesday, November 23, 2016 1:21 PM, tuxor1337 <notifications@github.com> wrote:
 

 3.14 is no longer supported, sorry.—

**Comment by tuxor1337** [comment]
metadata.json hasn't listed 3.14 since August 2016: https://github.com/mlutfy/hidetopbar/commit/da30ca70e4dc8c376025905a4b0621187fb1aa51

**Comment by gnarendran** [comment]
Hmm ok, you are right as per git. But I am not sure why:
a) still the extension was updated by gnome-shell-extension without considering my version of 3.14.4b) only some of the files (e.g, intellihide.js) got updated but not metadata.json:
> cat ~/.local/share/gnome-shell/extensions/hidetopbar\@mathieu.bidon.ca/metadata.json{   "_generated": "Generated by SweetTooth, do not edit",  "description": "Hides the top bar, except in overview. However, there is an option to show the panel whenever the mouse pointer approaches the edge of the screen. And if \"intellihide\" is enabled, the panel only hides when a window takes the space.",  "name": "Hide Top Bar",  "settings-schema": "org.gnome.shell.extensions.hidetopbar",  "shell-version": [    "3.8",    "3.10",    "3.12",    "3.14",    "3.16",    "3.18",    "3.20"  ],  "url": "https://github.com/mlutfy/hidetopbar",  "uuid": "hidetopbar@mathieu.bidon.ca",  "version": 52
May be the gnome repository's version is different in some way or there is a bug in the update process. Probably nothing you could do. Thanks for responding anyway!
Regards,Narendran Gopalakrishnan. 

    On Thursday, November 24, 2016 1:47 PM, tuxor1337 <notifications@github.com> wrote:
 

 metadata.json hasn't listed 3.14 since August 2016: da30ca7—

**Comment by tuxor1337** [comment]
Everything is fine about your version: You are now on version 52, which is the latest version from extensions.gnome.org that supports 3.14. Unfortunately, when we dropped support for 3.14, there were unresolved bugs concerning this version. (Actually, that was the original reason for abandoning 3.14 support.)
