### ISSUE TITLE
Extension does not work after updating Fedora24 -> Fedora25

### ISSUE THREAD

**Issue by fredrikekre** [mlutfy/hidetopbar#118]
Upgraded from Fedora24 to Fedora25 the other day and since that the extension won't load.

![screenshot from 2016-11-29 09-36-44](https://cloud.githubusercontent.com/assets/11698744/20702288/755b98e0-b617-11e6-9b15-ee8c4a40f9df.png)

Hovering over the triangle says: "Error loading extension"

**Comment by tuxor1337** [comment]
I'm on Fedora 25, but from a clean install. I can't reproduce this. Please remove the extension and reinstall the latest version from extensions.gnome.org. Furthermore, please specify your hidetopbar-settings as well as all other installed extensions.

**Comment by fredrikekre** [comment]
Installed extensions:

![screenshot from 2016-11-29 10-01-51](https://cloud.githubusercontent.com/assets/11698744/20703151/f739d9f0-b61a-11e6-93d3-d7e29f6b902a.png)

Hide top bar settings (haven't touched them since the reinstall)

![screenshot from 2016-11-29 10-06-08](https://cloud.githubusercontent.com/assets/11698744/20703310/8d921ee4-b61b-11e6-86f6-54cf2fc802ea.png)


Already tried to remove and reinstall.

**Comment by fredrikekre** [comment]
Completely removed Gnome Tweak Tools and reinstalled, still the same problem.

**Comment by tuxor1337** [comment]
Are you on Wayland or on X? Did you try deactivating all other extensions and logging off and on again?

**Comment by fredrikekre** [comment]
Removed `Hide top bar`, deactivated all extensions, logged off and in again. Installed `Hide top bar` again, but still the same problem.

```sh
fredrik@fredrik-laptop ~ $ loginctl
   SESSION        UID USER             SEAT            
         2       1000 fredrik          seat0           
        c1         42 gdm              seat0           

2 sessions listed.
fredrik@fredrik-laptop ~ $ loginctl show-session 2 -p Type
Type=wayland
```

**Comment by fredrikekre** [comment]
Played around some with the settings, and although the extensions says it doesn't load some weird stuff is going on. I activated "Show panel when mouse approaches edge of screen", and that made the top bar disappear. But can not get the bar back now.

If I keep the setting above and also activate `In the above case show overview too` the overview is shown when the mouse approaches the edge, but the bar is still hidden.

**Comment by tuxor1337** [comment]
If possible, please provide the output of

    journalctl /usr/bin/gnome-shell -f -o cat

which will hopefully contain some error messages produced by hidetopbar.

**Comment by fredrikekre** [comment]
Output:

```sh
fredrik@fredrik-laptop ~ $ journalctl /usr/bin/gnome-shell -f -o cat
STACK_OP_ADD: window 0x1e00366 already in stack
STACK_OP_ADD: window 0x1e00383 already in stack
STACK_OP_ADD: window 0x1e00383 already in stack
STACK_OP_ADD: window 0x1e003b6 already in stack
STACK_OP_ADD: window 0x1e003b6 already in stack
STACK_OP_ADD: window 0x1e003bc already in stack
STACK_OP_ADD: window 0x1e003bc already in stack
STACK_OP_ADD: window 0x1e003c2 already in stack
STACK_OP_ADD: window 0x1e003c2 already in stack

```

**Comment by tuxor1337** [comment]
Okay, I'm out. I cannot reproduce this however closely I follow your description of the setup. Plus, there are no error messages. The last thing, I can think of now: Create a new user account on your system with a completely clean $HOME directory and try to reproduce your issue there.

**Comment by fredrikekre** [comment]
I created a new user and installed the extension and it worked. Is there some kind of stored data in my current user that I need to reset maybe?

Also: When I logged back into my real user, the bar was back, and then again, when I turned on the `Keep  hot corner sensitive, even in hidden state` the bar is gone again, like my previous comment.

**Comment by tuxor1337** [comment]
The only data touched by this extension are the dconf settings in `/org/gnome/shell/extensions/hidetopbar/`. You can reset those for your current user using the commandline:

    dconf reset -f /org/gnome/shell/extensions/hidetopbar/

**Comment by fredrikekre** [comment]
Removed extension, reset the config with your line above, logged off and on, installed extension, but still the same problem. This is strange...

**Comment by FMuro** [comment]
It really strange. I'm also on F25 (updated from several previous versions) and I haven't got any similar problem.

**Comment by fredrikekre** [comment]
@FMuro did you upgrade it or completely reinstalled it?

**Comment by FMuro** [comment]
I always upgrade, with fedup before, just gnome software these days.

**Comment by alan12345678** [comment]
Umm, yup - mine has just this minute broken too! Completely new install of F25, but it WAS working fine for past couple of hours, and now suddenly - small [i] icon beside it in the gnome-tweak-tool. Going to the extensions webpage gives the same "error" button as above. Followed your instructions above to reset config, but no joy. It's suddenly broken for no reason I can think of.

Some odd behaviour: The top bar is now again permanent. With tweak tool open and then editing settings for this extension, if I switch "keep hot corner sensitive, even in hidden state" then the bar hides. But, once it unhides, it's again stuck.

So it's 'sort-of-working' but not quite. No idea why? The only thing I've done is locally installed Aptana, but can't imagine how that's had any affect.

Can I build locally? Will that cure it? Suddenly it's a massive annoyance to have this broken ;0)

**Comment by alan12345678** [comment]
Update to yesterday's comment: working again now! The issue *was/must have been* something connected to using nvidia drivers via rpmfusion. Why? Because this morning there were new updates for all of their xorg-x11-nvidia-* (including i686) and when I reinstalled this extension, it worked perfectly.

**Comment by jacknlliu** [comment]
I met the same error too with Fedora 25 wayland and gnome-shell-3.22.2. I used the intel graphic driver with intel core i7 cpu.

**Comment by fdelapena** [comment]
This happens to me while trying to use it with multiple monitors. See #136.

**Comment by tuxor1337** [comment]
This bug seems to be outdated/resolved/... Reopen if it still applies to you.

**Comment by fredrikekre** [comment]
I currently use Ubuntu, and this is not a problem, so I won't be able to supply any useful information anyway.

**Comment by jacknlliu** [comment]
@tuxor1337  Did you fix this issue? It still exists from my side. And did anyone get the point of this issue?

**Comment by tuxor1337** [comment]
@jacknlliu I have been using Fedora (currently 26) with GNOME and Intel graphics driver every day for years and I was never able to reproduce this. Have you been able to reproduce it? That is, are you able to give step by step instructions for how to reproduce this with a freshly installed Fedora? Does it also apply to new users on your machine or only to the existing one? I'm asking because it looks to me like this is a matter of misconfiguration in third-party software that nobody can reproduce at will.

**Comment by jacknlliu** [comment]
I can confirm this issue still exist on Fedora 25 with latest packages. Just `remove this plugin and reinstall` or  `using a new user and install` not working!

**Comment by jacknlliu** [comment]
Okay, definitely, for the first time I install the plugin, it seems work well. But after I reboot the system, it will fail.
