### ISSUE TITLE
Can't unhide top bar if there are any fullscreen windows

### ISSUE THREAD

**Issue by damag** [mlutfy/hidetopbar#119]
To test, I start Firefox and hit F11 to fullscreen it. After doing so I can no longer access the top bar, even if Firefox is not the currently focused application. Maximizing does not cause this problem.

**Comment by tuxor1337** [comment]
What do you mean by "can no longer access the top bar"? What do you mean by "access"?

Would you please specify your setup? Version of GNOME, other installed GNOME extensions and your hidetopbar settings, ...?

**Comment by damag** [comment]
Sorry about the lack of details. What I mean is that normally I can move my mouse pointer to the top of the screen and the top bar will show itself. When I have an app that is fullscreen, moving my mouse pointer to the top of the screen does nothing.

I'm running an up-to-date Arch Linux machine which uses GNOME 3.22.2. My installed extensions are:

- AlternateTab
- Hide Top Bar
- Launch new instance
- OpenWeather

And my hidetopbar settings:
![screenshot from 2016-12-02 16-46-49](https://cloud.githubusercontent.com/assets/165902/20840040/2d51b4ae-b8af-11e6-81bf-a56cfa8b632a.png)

Please let me know if I can provide anything else, thanks.

**Comment by tuxor1337** [comment]
This is intended behavior. The idea of fullscreen mode is to suppress stuff like the top bar. Quite naturally, the top bar will be covered by fullscreen mode application if you are not using this extension. 

However, pressing the keyboard shortcut that you can define in the hidetopbar settings you can actually access the top bar. Maybe that's an option for you?

**Comment by damag** [comment]
Yea I see your point, but I guess I would expect a fullscreen app like a game to only cover the desktop's UI when that app is the currently focused application. Sometimes I have a fullscreened editor or terminal window hidden somewhere in the background and I forget that the top bar won't work because of them. But you're right, that's not how GNOME seems to work so I can't expect this extension to change that. I'll have to make due with a hotkey for now. Thanks.
