### ISSUE TITLE
Panel Hides when Notification Appears

### ISSUE THREAD

**Issue by randomrarehunter** [mlutfy/hidetopbar#122]
When playing music, everytime the song changes gnome shows a notification of the new song that's being played. This causes the top bar to hide when the notification tab appears.

Running Arch Linux 64-bit
Gnome version - 3.22.2
Gnome Shell Version - 3.22.2-1
![screenshot from 2016-12-08 16-00-05](https://cloud.githubusercontent.com/assets/24465675/21032653/b2d61fc0-bd5f-11e6-967d-0fe4fc1d0fab.png)

**Comment by tuxor1337** [comment]
This is intended behavior: https://github.com/mlutfy/hidetopbar/issues/74

**Comment by xuiqzy** [comment]
I understand that cutting the notification off by not hiding would be bad and this is better.
But couldn't we move the position of the notification being displayed down to the normal position when the top panel is visible?
Or why is that not desirable?

**Comment by tuxor1337** [comment]
If you know how to do that, you can create a pull request. Then we can discuss how much effort will be needed to support this with future GNOME version updates (API changes etc.).
