### ISSUE TITLE
shortcut top bar

### ISSUE THREAD

**Issue by murpholinox** [mlutfy/hidetopbar#126]
Sorry this will be more like a question because I am not sure if this is really an issue.
Is is possible to cancel the shortcut for "Key that triggers the bar to be shown"?
I use ctrl-X and it was impossible to copy things in libreoffice or almost any other app. (very fool)
Then I choose something more difficult like ctrl+windowskey+o ...but then I find out that I can move the mouse to the top and the bar will appear. 
So I do not need anymore the shortcut but I am not sure how to cancel it. I have removed and reinstalled the extension but it remembers the old shortcut. 
Thanks

**Comment by tuxor1337** [comment]
Don't worry, you are not the first to ask this: https://github.com/mlutfy/hidetopbar/issues/77 The answer is: use the backspace key to remove your shortcut.

**Comment by murpholinox** [comment]
:P Thanks a lot.
