### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by mnwstl** [mlutfy/hidetopbar#131]
Hello! I would like to translate into Portuguese from Brazil. It is possible? How can it be done? Thank you!

**Comment by tuxor1337** [comment]
Great!
* You start from the GetText template file in [locale/hidetopbar.pot](https://github.com/mlutfy/hidetopbar/blob/master/locale/hidetopbar.pot).
* Here is an example of what it's supposed to look like when finished: [locale/fr/LC_MESSAGES/hidetopbar.po](https://github.com/mlutfy/hidetopbar/blob/master/locale/fr/LC_MESSAGES/hidetopbar.po).
* And here is an introduction to the usage of GetText PO and POT files: https://www.drupal.org/node/1814954

**Comment by mnwstl** [comment]
I am sending the file pt_BR.po and pt_BR.mo with the translation into Portuguese / Brazil. Thank you!

[pt_BR.tar.gz](https://github.com/mlutfy/hidetopbar/files/917759/pt_BR.tar.gz)

**Comment by tuxor1337** [comment]
Thanks!
