### ISSUE TITLE
Shell crash

### ISSUE THREAD

**Issue by ddnexus** [mlutfy/hidetopbar#132]
It was working fine on 16.10 (even Wayland) but it badly crashes in Ubuntu 17.04.

**Comment by tuxor1337** [comment]
There already was a bug report about GNOME 3.24 in #128 and I thought we solved the problems.

@corebots Can you confirm this?

**Comment by ddnexus** [comment]
OK, so... sorry to have missed all that details, but I didn't wanted to waste time in case you already knew. The bug is somehow similar to issue #128. The first time it raised the same error reported. Then I removed it, and after a while I reinstalled it, and it froze the shell completely., and I had to hard-restart.. maybe that is some interaction with other extensions (that I was trying at that time)?

I installed it with the browser from extensions.gnome.org. How does that work? Is the downloaded code the one in this repo, or it is an archive that has to be uploaded there? Because if it has been fixed, maybe I didn't get the fix from the extensions site. Just guessing though...

**Comment by ddnexus** [comment]
Just retried it. As soon as it is installed it initially hide the top bar. But it doesn't appear anymore even with the pointer on it. Then it switches off (not sure it was the old setting stuck to off). Trying to open the settings, gives the same error of #128.
HTH

**Comment by ddnexus** [comment]
It does not crash it anymore... and it partially works: it hides and show the bar by moving a window in and out the the bar space, however there is no way to get to the settings, and it does not show up with the pointer.

**Comment by tuxor1337** [comment]
For the fix of #128 you have to either use the version from Github or you have to wait for the review process on extensions.gnome.org to finish: https://extensions.gnome.org/review/6737

**Comment by danslo** [comment]
I can also confirm this issue. There's a gnome-shell report here:
https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1681822

**Comment by tuxor1337** [comment]
Because this issue is somehow mixed up with #128, I refer everyone to the new issue #134 that seems to address the second issue discussed here.
