### ISSUE TITLE
Show toppanel on the toppest level

### ISSUE THREAD

**Issue by colben** [mlutfy/hidetopbar#139]
Can the toppanel show on the toppest level like "dash-to-dock" ?
I offen run win7 in vbox with full screen, and the the "dash-to-dock" panel can slide out when I move mouse to the left border of screen.
[here is the picture](http://i4.piimg.com/600088/c6c354773699a058.png)
with "hide-top-bar", the top panel can not show out when I move mouse to the top border of screen.

**Comment by corebots** [comment]
indeed it would be nice to have the top bar always accessible, even from full-screen windows. Together with dash-to-dock that would serve for perfectly handled uncluttered experience all the time :) please implement

**Comment by tuxor1337** [comment]
When activated in the preferences, the panel is accessible even from full-screen windows. This is a non-issue.
