### ISSUE TITLE
not work well with google chrome browser

### ISSUE THREAD

**Issue by ljhui** [mlutfy/hidetopbar#141]
I use fedora 24 with GNOME Shell 3.20.4, the intellhide functionality not work well when chrome browser is full screen,when I approach the edge of screen, it often fail to  toggle the bar , other software works well, for full screen firefox browser ,it behaves well ,only fails in chrome browser, I don't know why ,how can I solve it? in addition, I use this extension with dash to panel extension.

**Comment by sonejizrelax** [comment]
+1!!! i have this issue too, it seems to just not work with chrome :( I have tried it with "use system title bar and borders" off as well as on and the issue persists. Sometimes "Ctrl+Shift+Q"ing chrome and restarting it helps but not always

**Comment by y-usuzumi** [comment]
Having this issue too.

Some interesting points:
1. Can workaround this by disabling "hardware acceleration" in chrome;
2. kimpanel-for-gnome-shell will not work correctly either in chrome when hit by this issue.

**Comment by thatside** [comment]
Same setup as @ljhui. 
By the way, it works OK while second screen is connected - so it appears only while using only one screen.
