### ISSUE TITLE
Gnome 3.26 support

### ISSUE THREAD

**Issue by gregd** [mlutfy/hidetopbar#145]
Does the extension work with Gnome 3.26? 

Today I tried it with Ubuntu 17.10 and nothing happens after installation. I added `3.26` to the metadata.json file however this doesn't change anything. Actually I don't known if I installed the extension correctly. The `gnome-shell-extension-tool -e ...` seems to accept any string as extension name so I guess it also doesn't verify anything.

**Comment by mattdm** [comment]
It is working for me in 3.26.1 in Fedora 27 beta.

**Comment by gregd** [comment]
OK, the extension directory must be cloned to `hidetopbar@mathieu.bidon.ca`. Now it works.
