### ISSUE TITLE
Bar doesn't rehide on slow mouse-out

### ISSUE THREAD

**Issue by guzzard** [mlutfy/hidetopbar#147]
Most of the time the top bar auto hides again after being shown, for example when switching window or starting an application, or clicking one of the systray icons, but sometimes it does't hide as it should. I then have to move the mouse pointer to the top of the screen again and down just to get it to hide. Seems random, cannot reproduce it reliably.

**Comment by tuxor1337** [comment]
Which version of GNOME are you using? Which GNOME extensions do you use apart from Hide Top Bar? Anybody else experiencing this?

**Comment by guzzard** [comment]
Hi @tuxor1337,

GNOME 3.26.2

**Other activated extensions are:**
Frippery Move Clock
KStatusNotifierItem/AppIndicator Support
OpenWeather
Panel OSD
Put Windows
Sound Input & Output Device Chooser
Suspend Button
system-monitor
TaskBar
TopIcons Plus
User Themes
'Window Is Ready' Notification Remover

For me it's possible to provoke the issue to happen, see the attached video: [hide_top_bar_issue.mp4.zip](https://github.com/mlutfy/hidetopbar/files/1487819/hide_top_bar_issue.mp4.zip)

**Comment by RomanBruhanov** [comment]
I can confirm one case of not hiding the panel.
GNOME Shell 3.26.2 on Debian 9 testing, only this extension active
Settings for extension:
from top to bottom
Show panel when mouse approaches edge of the screen ON
then
Keep hot corner... OFF
In the above case show overview... OFF
Pressure threshold 0
Pressure timeout 0
Animation settings DEFAULT (0,4/0,2)
then
Key trigger DISABLED
Delay 0
Rehide ON
and
Intellihide BOTH OFF

How to reproduce bug:
-Move mouse pointer to the top of the screen, revealing top panel
-Slowly (SLOWLY!) move mouse pointer away from top panel
Top panel will not hide.

This behavior is related to speed of mouse pointer, exceeding some speed threshold top panel is hiding.

**Comment by ainar** [comment]
> How to reproduce bug:
> -Move mouse pointer to the top of the screen, revealing top panel
> -Slowly (SLOWLY!) move mouse pointer away from top panel
> Top panel will not hide.
> 
> This behavior is related to speed of mouse pointer, exceeding some speed threshold top panel is hiding.

I have exactly the same issue now.

**Comment by SkipHendriks** [comment]
> How to reproduce bug:
> -Move mouse pointer to the top of the screen, revealing top panel
> -Slowly (SLOWLY!) move mouse pointer away from top panel
> Top panel will not hide.
> 
> This behavior is related to speed of mouse pointer, exceeding some speed threshold top panel is hiding.

Same issue on Fedora 30 running Gnome 3.32.2

**Comment by Fushko** [comment]
>     How to reproduce bug:
>     -Move mouse pointer to the top of the screen, revealing top panel
>     -Slowly (SLOWLY!) move mouse pointer away from top panel
>     Top panel will not hide.

I can reproduce on 3.34.1. Mouse movements don't have to be that slow. 
Doesn't seem dependent on any particular setting. It goes back up only when moving the mouse on the top edge of the screen again.

**Comment by yoyoma2** [comment]
Reproducible on ubuntu 18.04 LTS with gnome shell version 3.28.4-0ubuntu18.04.3.  As others have stated, moving the mouse out of the top bar very slowly guarantees the bug will occur.
