### ISSUE TITLE
Can't transition between monitors if they are "stacked"

### ISSUE THREAD

**Issue by jm-duarte** [mlutfy/hidetopbar#148]
Hey there! 
I'm using the version installed through the GitHub README tutorial on GNOME 3.26.1 (Ubuntu 17.10)
It is impossible to transition between monitors with the following configuration.

![screenshot from 2017-10-29 19-47-46](https://user-images.githubusercontent.com/15343819/32147611-1506836a-bce2-11e7-9145-a1e0739ebd3b.png)

The only way I made it work is through deactivating the "auto-show" and using a keyboard shortcut, which is really inconvenient.
Thank you!

**Comment by tuxor1337** [comment]
Sorry, we won't support this setup: https://github.com/mlutfy/hidetopbar/issues/100
