### ISSUE TITLE
Minimum monitor resolution for triggering

### ISSUE THREAD

**Issue by gfiorav** [mlutfy/hidetopbar#152]
First of all, thanks for this amazing extension. It's one of the finer pieces of work I've seen in Gnome, congrats.

## Context

I use this extension to save space on my X270's small screen. I'm sure I'm not the only one!

When I plug my external monitor in, though, I feel it's unnecessary. It would be amazing if the extension could be configured to trigger on minimum screen height. That way, it will only kick in when really needed (on a small screen).

There're are my two cents! I could give it a go too, if you'd like, and submit a PR. Thanks again.

**Comment by tuxor1337** [comment]
I don't think it makes sense to implement this as a feature of HideTopBar. You should rather write a script that detects a change of resolution and decides whether to de-/activate HideTopBar from the command line.

**Comment by gfiorav** [comment]
Sure, this could be achieved with a script. I just felt it would be a great addition for users trying to save some space on small screens, but really not be bothered on external/bigger ones.

**Comment by tuxor1337** [comment]
Yes, it definitely is a nice addition! :+1:  But there's no reason why you would integrate this addition into Hide Top Bar (keep it small and simple, right?). Feel free to write a script and put it on your gist or somewhere else online so that people can use it. :)

**Comment by gfiorav** [comment]
Agreed, thanks!
