### ISSUE TITLE
Debian 9.3 Resize Window

### ISSUE THREAD

**Issue by JeCosVi** [mlutfy/hidetopbar#155]
Hi, there is a problem when you resize the window in Debian 9.3, the tittle's bar doesn't hide. Only happen when you resize the window to the minimun size.
![rect3684](https://user-images.githubusercontent.com/17854097/36422378-082eab5a-163c-11e8-9ee0-44998d623651.png)

**Comment by tuxor1337** [comment]
You are talking about the window title bar whereas this extension is about GNOME's top panel. Maybe you confused the purpose of this extension with the functionality of extensions like Maximus (Two) or Pixel Saver...?

**Comment by JeCosVi** [comment]
Sorry, I have had an error I have confused this extension with this one, https://github.com/franglais125/no-title-bar/
