### ISSUE TITLE
allow show over fullscreen apps

### ISSUE THREAD

**Issue by rkitover** [mlutfy/hidetopbar#157]
Dash To Dock has a nice feature where moving the mouse to the dock edge shows the dock even when a fullscreen app like e.g. Terminator in full screen mode is running, would be nice to have this feature for this extension as well!

**Comment by tuxor1337** [comment]
Eventually, it would make sense to have the whole thing implemented as just another Dash to Dock panel. This would immediately solve many of the incompatibilities and benefit a lot from the active development in the Dash to Dock extension. On the other hand, the Dash to Dock code has grown so complicated by now that I will probably never find the time to look into this...

**Comment by peter-kehl** [comment]
Hi Thomas,

For your reference: in Dash to Dock, autohide in fullscreen mode is controlled by `autohide-in-fullscreen`. See https://github.com/micheleg/dash-to-dock/blob/master/docking.js.

**Comment by bretello** [comment]
Thanks for the comment @tuxor1337, I took some time and created a pull request implementing this (#186)
