### ISSUE TITLE
GNOME 3.29 drops MetaScreen

### ISSUE THREAD

**Issue by coldtobi** [mlutfy/hidetopbar#162]
I've bug got this report in Debian: #905111 (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=905111)

Quote:

> According to codesearch.debian.net, this extension uses the MetaScreen
> via global.screen. MetaScreen no longer exists in GNOME 3.29, which is
> starting to become available in experimental. This extension will need
> code changes to use the MetaDisplay (global.display),
> MetaWorkspaceManager (global.workspace_manager), MetaMonitorManager
> (Meta.MonitorManager.get()) or MetaX11Display
> (global.display.get_x11_display()).
> 
> Because GNOME 3.29/3.30 is not a stable release yet and is not in
> Debian unstable yet, you'll probably need to condition on the GNOME
> Shell version.
> 
>     smcv

**Comment by tuxor1337** [comment]
For reference: https://gitlab.gnome.org/GNOME/gnome-shell/commit/47ea10b7c976abb1b9ab4f34da87abb1e36855fe
