### ISSUE TITLE
Optionally hide top bar in overview

### ISSUE THREAD

**Issue by lukasbash** [mlutfy/hidetopbar#164]
Would it be possible to add an option to disable the top bar in overview mode as well?
I am using polybar and it is quite ugly if both of the bars overlap.

I think this would be a cool feature for other users as well!

**Comment by noobestskid** [comment]
yes i need this feature as well!

**Comment by p3732** [comment]
Related to #149, since normal dash does not interfere with top bar.

**Comment by tuxor1337** [comment]
Feature added in PR #264
