### ISSUE TITLE
Gnome version 3.30 bump

### ISSUE THREAD

**Issue by ILMostro** [mlutfy/hidetopbar#166]
Does not work with gnome-3.30

```
gnome-shell[1770]: Extension "hidetopbar@mathieu.bidon.ca" had error: TypeError: object is undefined
```

**Comment by trinaldi** [comment]
I was having the same problem, all I did was toggle ON/OFF the extension from the [GNOME Extensions site](https://extensions.gnome.org/extension/545/hide-top-bar/).

Seems to be working.

**Comment by albfan** [comment]
Not working here too! Any test or feedback I can provide?

**Comment by albfan** [comment]
I have the extension installed by a package `gnome-shell-extensions`

    /usr/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/

and by user selection (from website)

    $HOME/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/

Just removed all them and reinstall from user selection. It works again

**Comment by Madis0** [comment]
Seems to work for me when I disable Intellihide.

**Comment by David-Else** [comment]
Can I safely use the current version with Fedora 29/gnome-3.30.2, or do we need an urgent update? Thanks.

**Comment by David-Else** [comment]
@tuxor1337 The reason I ask is here:

https://extensions.gnome.org/extension/545/hide-top-bar/

The top two comments say it does not work in gnome 3.30 and Fedora 29, and this thread contains what seems like some 'hacks' to make it work. I am wondering if it is officially supported, would be great to hear from one of the extensions authors... outdated extensions are infamous for causing Gnome stability problems, and that is the last thing anyone wants.

**Comment by albfan** [comment]
@David-Else this is the main repo pointed on official extensions website. It should just work.

If anything fails check those dirs, maintainer for this extension has no control on downstream packages distributed with any possible distro.

**Comment by David-Else** [comment]
Cheers guys!

**Comment by David-Else** [comment]
@tuxor1337 @albfan Seems to be working great with Intellihide off :)

**Comment by tuxor1337** [comment]
I'm now on Fedora 29 and not able to reproduce this. Maybe you have an issue with Fedora's upgrade mechanism. Hide Top Bar seems to be perfectly compatible with Gnome 3.30 - no issues with intellihide in my case.
