### ISSUE TITLE
No such schema “org.gnome.shell.extensions.hidetopbar”

### ISSUE THREAD

**Issue by Boycce** [mlutfy/hidetopbar#168]
I am trying to install `hidetopbar` manually, and when i try to set some settings via command line e.g  `gsettings set org.gnome.shell.extensions.hidetopbar animation-time-autohide 0.1`, i receive the error below.

> No such schema “org.gnome.shell.extensions.hidetopbar”

**Comment by p3732** [comment]
This is the for all the extension settings and not specific to hidetopbar. I don't know where best to report this, probably against [gnome-shell](https://gitlab.gnome.org/GNOME/gnome-shell/issues).

**Comment by tuxor1337** [comment]
Closing this with regards to https://askubuntu.com/questions/490939/configure-gnome-shell-extensions-from-command-line
