### ISSUE TITLE
Not working on Gnome 3.30 (Wayland)

### ISSUE THREAD

**Issue by kllp** [mlutfy/hidetopbar#169]
SyntaxError: redeclaration of let settings_vbox

Stack trace:
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:67:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:82:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
  @<main>:1:43
  
I feel so sad because Gnome has **no** setting to hide the top bar. It's unbelievable to me as this is one of the most basic interface requirements.
To make matters worse some extensions don't work as they are supposed to.

**Comment by Chris-YBS** [comment]
Just upgraded to Fedora 29 and I have the same issue!

**Comment by tuxor1337** [comment]
I can't reproduce this on Fedora 29 and the error message doesn't seem to make any sense since `settings_vbox` is only declared once.
