### ISSUE TITLE
Must be restarted to work on fresh boot.

### ISSUE THREAD

**Issue by Chronigan** [mlutfy/hidetopbar#176]
In order to get the extension to work correctly after a fresh boot, I must restart the extension.

**Comment by rliou92** [comment]
I experience this issue as well.

**Comment by newptcai** [comment]
This happens to me if I start the system with an external monitor connected. Is there a way to write a script to do this switching off/on automatically?

**Comment by Chronigan** [comment]
I have the following script that I use.
`#!/bin/bash

ExitCode=1

while [ "$ExitCode" -eq "1" ] ; do
	if gnome-shell-extension-tool -r hidetopbar@mathieu.bidon.ca ; then
		ExitCode=0
		else
			sleep 5s
	fi
done`

And I also use the following *.desktop file in my ~/.config/autostart directory
`[Desktop Entry]
Version=1.0
Type=Application
Name=rtopbar
Comment=rtopbar
Exec=rtopbar
Terminal=false
StartupNotify=false`

So it restarts automatically for me on login.

**Comment by newptcai** [comment]
This solves my problem. Thanks.
