### ISSUE TITLE
Make it available for gnome 3.32

### ISSUE THREAD

**Issue by Jbbouille** [mlutfy/hidetopbar#185]
https://github.com/mlutfy/hidetopbar/blob/8cca3d4fb12c96d9797e0b9a896756026c05d02d/metadata.json#L2
Would it be possible to make it available for gnome 3.32 ?

**Comment by tuxor1337** [comment]
It's already available on GNOME 3.32. Installing an extension on any GNOME version does not require the specific version to be listed in metadata.json. This is controlled by `org.gnome.shell.disable-extension-version-validation` in dconf.
