### ISSUE TITLE
Topbar overlaps dock

### ISSUE THREAD

**Issue by pabloz** [mlutfy/hidetopbar#187]
Topbar overlaps dock, please see the top-left corner in this image:

![Screenshot from 2019-08-19 09-49-24](https://user-images.githubusercontent.com/5929558/63269028-d7d72080-c26b-11e9-8179-b68fdedfcb5b.png)

Any workaround?
I think this could be solved adding an option to add some extra space at the top of the dock.

Ubuntu 19.04
Gnome 3.32.1

Thank you!

**Comment by tuxor1337** [comment]
Closing as duplicate of https://github.com/mlutfy/hidetopbar/issues/149
