### ISSUE TITLE
Unable to locate GNOME Shell settings or version. Make sure it is installed and running.

### ISSUE THREAD

**Issue by feifeiwei** [mlutfy/hidetopbar#192]
wrong with firefox, please help me.

**Comment by tuxor1337** [comment]
I don't understand what's your issue. Please give step by step instructions on how to reproduce.

**Comment by feifeiwei** [comment]
![2019-10-08T06-36-08 869Z](https://user-images.githubusercontent.com/40533960/66372622-0904df00-e9d9-11e9-9cef-88ddb930ac39.png)

**Comment by feifeiwei** [comment]
i install gnome extension in firefox, but it occur a mistake like the above pictures

**Comment by tuxor1337** [comment]
That's not related to this extension. Please contact your distribution's support.
