### ISSUE TITLE
Panel overlaps with notifications with intellihide

### ISSUE THREAD

**Issue by otsaloma** [mlutfy/hidetopbar#198]
Using GNOME ~3.34.1 on Debian unstable. Since some recent update, notifications now appear below the panel when using intellihide.

![Screenshot from 2019-12-01 22-40-48](https://user-images.githubusercontent.com/237265/69920031-de407f80-148b-11ea-9bd1-7d9f3b274027.png)

**Comment by AdoniasAlcantara** [comment]
Same to me on Ubuntu 19.10 (GNOME 3.34.1)

**Comment by tuxor1337** [comment]
Okay, this seems to be a regression from https://github.com/mlutfy/hidetopbar/commit/35fc9201e0b927fb676d7ef123e02506fc8d04bb

**Comment by mapuo** [comment]
This fix clashes with the Panel OSD extension.
Top image is when a application is hiding the top panel, bottom is when the top panel is visible.
![panelosd](https://user-images.githubusercontent.com/99132/82649349-b6073180-9c21-11ea-8367-08a42fa78a28.png)

**Comment by xuiqzy** [comment]
Now, the panel is hidden just for the notification to display and comes back when the notification disappears, which seems really awkward.
Should I open a new issue for that?

**Comment by tuxor1337** [comment]
@xuiqzy No, it's intended behavior: #74 #122

**Comment by xuiqzy** [comment]
Oh thanks, sorry for not searching!
