### ISSUE TITLE
Tooltips from inactive windows overlap active window

### ISSUE THREAD

**Issue by Aceler** [mlutfy/hidetopbar#208]
Ubuntu 19.10, Gnome 3.34, Wayland

Open two windows, make one window active. Hover mouse cursor over some elements of the inactive window that spawn a popup. Make sure, that the popup appears and overlap the active window.

In this scenario, the inactive window will overlap the active as well as the popup. This shouldn't be.

See the screenshot here. The popup from inactive Evince overlapped active nautilus window and cause evince to overlap nautilus, while nautilus is still active:
![Снимок экрана от 2020-03-25 15-31-56](https://user-images.githubusercontent.com/5177608/77553880-6d9ff180-6ec6-11ea-9786-dc029cec806f.png)

If the popup is not overlap the active window, the bug will not happens.

**Comment by tuxor1337** [comment]
So, how is this related to the "Hide Top Bar" extension?

**Comment by Aceler** [comment]
It happens only when a "Hide top bar" extension is active.

**Comment by Aceler** [comment]
As long as I can say today, the bug doesn't exist anymore.
