### ISSUE TITLE
Restarting the Gnome shell after installing the extensions crashes the Gnome Xorg! 

### ISSUE THREAD

**Issue by javadr** [mlutfy/hidetopbar#211]
I installed the hidetopbar in Gnome 3.36.1 (Xorg) in Manjro. I was really impressed by its functionality but after relogin from auto lock screen, I lost the top bar. I had also set a key (super+b) to show/hide the top bar but that key didn't work.  Therefore, I tried to restart the Xorg (by alt+f2 -> r ). Unfortunately, the Xorg got stuck and never worked. More exactly, I can pass the login screen but after that my screen goes black and I can merely see a mouse pointer in a dark screen. I removed the extension manually from my gnome-shell directory and I restarted my laptop for several times but it didn't work! Now, the only choice that I have in my machine is to use Wayland and as you know some programs do not work properly in Wayland. 
How can I fix it? I really need Gnome on Xorg.

**Comment by tuxor1337** [comment]
If you removed the extension and it's still non-functional, I cannot assume that the problem is caused by this extension.

**Comment by javadr** [comment]
Thanks for your fast response. You're right. It might be another issue as I removed the extension and the problem exists afterward.
