### ISSUE TITLE
Error loading extension on Ubuntu 20.04

### ISSUE THREAD

**Issue by Bernardez** [mlutfy/hidetopbar#214]
Hi all,

On Ubuntu 20.04 LTS the extension would not load according to Gnome Tweaks.

Upon restarting Gnome Shell i get this log entry in my journal:
`JS ERROR: Extension hidetopbar@mathieu.bidon.ca: TypeError: PanelBox.get_anchor_point is not a function
                                        _updateStaticBox@/home/bas/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/panelVisibilityManager.js:260:33
                                        wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
                                        _init@/home/bas/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/panelVisibilityManager.js:65:14
                                        wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
                                        _Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:18:10
                                        newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:114:21
                                        enable@/home/bas/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/extension.js:26:18
                                        _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:166:32
                                        loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:336:26
                                        _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:577:18
                                        collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
                                        _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:552:19
                                        _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:586:18
                                        _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:617:18
                                        init@resource:///org/gnome/shell/ui/extensionSystem.js:55:14
                                        _initializeUI@resource:///org/gnome/shell/ui/main.js:257:22
                                        start@resource:///org/gnome/shell/ui/main.js:146:5
                                        @<main>:1:47`

**Comment by tuxor1337** [comment]
You seem to use an outdated version of HideTopBar. The function get_anchor_point has been removed already in Dec 2019: https://github.com/mlutfy/hidetopbar/commit/d7312b4d5dde5c186a56f20579736ee1a1544bf1
