### ISSUE TITLE
PanelBox.get_anchor_point is not a function

### ISSUE THREAD

**Issue by skurzinz** [mlutfy/hidetopbar#225]
Using v. 70 on gnome 3.36 under Fedora 32, I get the following error using gnome looking glass `lg`: 

> TypeError: PanelBox.get_anchor_point is not a function

and the extension does not load. 

Sorry that I don't even know how to make this reproducible…

**Comment by tuxor1337** [comment]
I'm on Fedora 32 and GNOME 3.36 and can't reproduce this. Furthermore, the function `get_anchor_point` is not used in the code of Hide Top Bar. Sorry, but without further information, we can't do anything about that.

**Comment by tuxor1337** [comment]
Probably a dup of #214
