### ISSUE TITLE
Hide the lower panel in classic mode.

### ISSUE THREAD

**Issue by Firstyear** [mlutfy/hidetopbar#23]
This extension could be easily extended to also allow automatic hiding of the task bar on the lower part of the screen in gnome 3 classic mode. The lower task bar is not shown in the activity window, so it would always need to behave as though it raises whenever the mouse approaches.

**Comment by tuxor1337** [comment]
I thought about it and I think that this is not the kind of thing that an extension with the name "hide top bar" should do. Keep it small & simple... or ... do one thing and do it well.
