### ISSUE TITLE
It should not remove gschema.xml file after installation

### ISSUE THREAD

**Issue by artu-hnrq** [mlutfy/hidetopbar#230]
**gschema.xml** files are useful for further manage of extension schema.
For example, allowing users to correctly compile it to `glib` properly directory, enabling `gsettings` cli schema manipulation, as [explained here][1]

  [1]: https://askubuntu.com/a/1246847/689894

**Comment by tuxor1337** [comment]
As mentioned in a comment to your linked web page:

> Typically the GNOME extensions installed by the user are installed in `$HOME/.local/share/gnome-shell/extensions`. Here you will find a folder for every extension. Inside every extension folder you'll find a folder called schemas where you find the gschema of that extension. This is the file to copy to `$HOME/.local/share/glib-2.0/schemas`. This means that usually the gschemas are already available, you should simply put them in the correct folder and compile them.

So, please just use the compiled gschema file provided with this extension.

**Comment by artu-hnrq** [comment]
Pretty nice! :clap: 
Thanks for have created and keep maintain this tool!
