### ISSUE TITLE
Switching monitors breaks auto hide

### ISSUE THREAD

**Issue by joveice** [mlutfy/hidetopbar#231]
Switching monitors breaks the auto hide, I have it happening all the time when I go away from my monitors and unplug my USB-C cable to them. Then it is permanently there overlapping everything. If I disable and enable the plugin the problem is gone. Happens when I connect back again too.

**Comment by tuxor1337** [comment]
Closing as a duplicate of https://github.com/mlutfy/hidetopbar/issues/154 and/or https://github.com/mlutfy/hidetopbar/issues/182
