### ISSUE TITLE
Gnome dock flickers on VLC

### ISSUE THREAD

**Issue by EmmanuelMess** [mlutfy/hidetopbar#232]
When VLC is windowed, and the window covers the whole desktop the dock flickers after a movie has been playing for a few minutes.

Ubuntu 20.04. Gnome 3.36.2. Hide top bar 72.

**Comment by EmmanuelMess** [comment]
Similar as #197.

**Comment by tuxor1337** [comment]
We now collect all reports about flickering in #197
