### ISSUE TITLE
failed install ubuntu 20.04

### ISSUE THREAD

**Issue by Mrian07** [mlutfy/hidetopbar#234]
GLib.FileError: Failed to open file “/home/mrian07/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/schemas/gschemas.compiled”: open() failed: No such file or directory

Stack trace:
  getSettings@/home/mrian07/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/convenience.js:86:31
  init@/home/mrian07/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/prefs.js:14:28
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:205:25
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ****

**Comment by bonedaddy** [comment]
I got this and running `make` fixed it

**Comment by tuxor1337** [comment]
Did you install from extensions.gnome.org? Can you give step by step instructions on how to reproduce this issue?

**Comment by bonedaddy** [comment]
I installed with with the [local install instructions](https://github.com/mlutfy/hidetopbar#local-installation). 

I also noticed that `make schemas` wasn't a valid command, and had to do `make` instead.
