### ISSUE TITLE
Top Bar doesn't hide any more on Debian Buster after last update

### ISSUE THREAD

**Issue by franzgratzer** [mlutfy/hidetopbar#235]
I am obviously not the only one having this issue: Since the last extension update (about a week ago) the top bar doesn't hide any more after it has been shown on Debian Buster with GNOME 3.30.2. The only way to get to what sits behind the top bar is to deactivate the extension.
I am unsure if Debian or the extension itself needs fixing to restore the original functionality, which I absolutely love.

**Comment by tuxor1337** [comment]
Thanks for the report! Sounds like we have to drop 3.30 support...

**Comment by franzgratzer** [comment]
Do you have any idea what might cause this? A lot of people use Debian Buster ... and will for quite some time. I have no idea how all this works together but maybe I can help in any way. I should be able to work with CSS but I don't know how GNOME creates interactive stuff. With Javascript?

**Comment by coldtobi** [comment]
> Do you have any idea what might cause this? A lot of people use Debian Buster ... and will for quite some time. I have no idea how all this works together but maybe I can help in any way. I should be able to work with CSS but I don't know how GNOME creates interactive stuff. With Javascript?

do you have the debian package installed or self-compiled?

**Comment by tuxor1337** [comment]
You don't really need a fix, as long as the old versions work for you. Only the current and future versions won't support 3.30.

**Comment by franzgratzer** [comment]
Great, thank you very much. After re-installation it now works again as intended. :)
