### ISSUE TITLE
Not working after the recent update

### ISSUE THREAD

**Issue by Xanaxus** [mlutfy/hidetopbar#239]
![image](https://user-images.githubusercontent.com/53279068/86317627-7e8e9a80-bc4d-11ea-9176-dbc18370b883.png)
as u can see the above image after updating the extension i am unable to use
![image](https://user-images.githubusercontent.com/53279068/86317686-ad0c7580-bc4d-11ea-9474-c998ef78bf3a.png)
![image](https://user-images.githubusercontent.com/53279068/86318575-f52c9780-bc4f-11ea-87ae-5a47328936de.png)

**Comment by tuxor1337** [comment]
Did you try logging off and on again? Did you try rebooting?

**Comment by Xanaxus** [comment]
nope let me try it

**Comment by Xanaxus** [comment]
yeah its working now
