### ISSUE TITLE
Just broke after the last commit

### ISSUE THREAD

**Issue by obi-wil** [mlutfy/hidetopbar#241]
Ubuntu 20.04 Gnome 3.36.2

**Comment by Coonaps** [comment]
Broke pop!OS 20.04 LTS Gnome 3.36.2

**Comment by tuxor1337** [comment]
This is not a bug report. It doesn't specify, what's the issue, steps how to reproduce it, exact information about setup (GNOME or Wayland, other extensions used, Hide Top Bar preferences, ...).
