### ISSUE TITLE
How to reset configuration to default?

### ISSUE THREAD

**Issue by wiany11** [mlutfy/hidetopbar#246]
Ah...

**Comment by tuxor1337** [comment]
The default values are in https://github.com/mlutfy/hidetopbar/blob/master/schemas/org.gnome.shell.extensions.hidetopbar.gschema.xml - does this help?

**Comment by wiany11** [comment]
Thanks!
But I still cannot disable `Key that triggers the bar to be shown.` How can I?

**Comment by tuxor1337** [comment]
You are not the first to ask this question: https://github.com/mlutfy/hidetopbar/issues/77
