### ISSUE TITLE
Translation for Portuguese of Brazil

### ISSUE THREAD

**Issue by mnwstl** [mlutfy/hidetopbar#248]
Hello!

I noticed that there is a revision of the translation for pt_BR, but on my system (ubuntu 20.04) always appears in English and I can not make it appear translated to pt_BR. Is there any way to get this right?

**Comment by mnwstl** [comment]
I found the problem. The file pt_BR.mo should be renamed to hidetopbar.mo in the source code folder.
Thank you!

**Comment by coldtobi** [comment]
Did you install the Debian package from the Ubuntu repository or via the Gnome extension site?
(https://launchpad.net/ubuntu/+source/gnome-shell-extension-autohidetopbar)
I have the Debian package installed and here it shows up in German…

**Comment by mnwstl** [comment]
> Did you install the Debian package from the Ubuntu repository or via the Gnome extension site?
> (https://launchpad.net/ubuntu/+source/gnome-shell-extension-autohidetopbar)
> I have the Debian package installed and here it shows up in German…

I installed from the GNOME extensions site. When I found that I wasn't translating, I compared the files of the various languages and found that all in their respective folders are hidetopbar.mo. That way it was just renaming the pt_BR.mo file hidetopbar.mo and everything normalized. I checked the ubuntu repository and found the same problem for Portuguese/Brazil. I would even ask the developer to review it in the source code.

**Comment by coldtobi** [comment]
(This is now fixed in the Debian package revision 20200628-2 , entering Debian unstable soonish [2] ) 

[1] https://salsa.debian.org/debian/gnome-shell-extension-autohidetopbar/-/tags/debian%2F20200628-2
[2] https://tracker.debian.org/pkg/gnome-shell-extension-autohidetopbar
