### ISSUE TITLE
Top Bar above the Dock 

### ISSUE THREAD

**Issue by hrittikhere** [mlutfy/hidetopbar#259]
The top bar is always above the Dock and it hides the Docked Elements like in the picture the Chrome Icon. It will be a  bettter option to allow the top bar sustain below the deck .

![image](https://user-images.githubusercontent.com/67012359/95885972-94a70d80-0d9b-11eb-95f9-7daa703126e6.png)

**Comment by tuxor1337** [comment]
Duplicate of #149
