### ISSUE TITLE
Settings don't work on GNOME 40

### ISSUE THREAD

**Issue by mattdm** [mlutfy/hidetopbar#268]
I disabled extension version validation and ... everything seems fine.

**Comment by mattdm** [comment]
Oh, wait, except: settings don't work:

````
TypeError: Gtk.VBox is not a constructor

Stack trace:
  buildPrefsWidget@/home/mattdm/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/prefs.js:37:17
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ````

**Comment by tuxor1337** [comment]
Thanks for checking! The settings should be fixed with the latest commit (under review on extensions.gnome.org).

**Comment by tuxor1337** [comment]
From a review on extensions.gnome.org:

> I noticed you have added support for GNOME 40 to your manifest, but parts of your UI file still use Gtk3 elements like &lt;packing&gt;. The preferences dialog in GNOME 40 will use GTK4, so your preferences will likely not work there without some modification.
>
> From glancing at your file it might be possible with a bit of compromise to support both, but you&#39;d have to do a bit of testing. We have a WIP page describing some of the differences at: https://gitlab.gnome.org/World/ShellExtensions/extensions-rebooted/-/blob/master/docs/GNOME40-Porting-Guide.md or you can join the Matrix channel to ask for help.

So, porting the settings dialog will probably remain an issue for some time...

**Comment by HideyoshiNakazone** [comment]
No problem, at least if extension version checking is disabled the extension can be installed and will partially work, thanks for the attention.

**Comment by stuzenz** [comment]
@mattdm Great extension - thanks for looking into this - re. Gnome40.

**Comment by ttys3** [comment]
new porting guide url: <https://gjs.guide/extensions/upgrading/gnome-shell-40.html>

**Comment by hzhangxyz** [comment]
I cannot use "Super+B" to toggle top bar, Since setting ui is not usable currently, I edit  `org.gnome.shell.extensions.hidetopbar.gschema.xml` manually as this:
```
    <key name="shortcut-keybind" type="as">
      <default><![CDATA[['<Super>b']]]></default>
      <summary>"show bar" shortcut</summary>
      <description>
        Keyboard shortcut that triggers the bar to be shown.
      </description>
    </key>
```
But it does not work.

**Comment by kmoad** [comment]
I've made a pull request that will hopefully resolve the settings issues on Gnome 40

#280

**Comment by tuxor1337** [comment]
Hey everyone, I merged @kmoad's changes (thanks a lot!), but don't have time to test it myself on a GNOME 40 setup. Would some of you please test with the latest version from git and confirm that the settings work?

**Comment by mattdm** [comment]
I installed with `make; gnome-extension install hidetopbar.zip` and it works but the settings fail with an error about not finding `Settings-40.ui`, which is not surprising because `Settings-40.ui` isn't getting put into the zip.  Copied into place and now it all seems to work.

**Comment by enetics-secker** [comment]
> Hey everyone, I merged @kmoad's changes (thanks a lot!), but don't have time to test it myself on a GNOME 40 setup. Would some of you please test with the latest version from git on GNOME 40 and confirm that the settings work?

Verified working in f34 gnome 40.  Had to disable version validation:

`gsettings set org.gnome.shell disable-extension-version-validation "true"`

**Comment by tuxor1337** [comment]
Thanks for your quick feedback! I added version `"40"` to the supported versions in metadata.json, added the `Settings-40.ui` to the zip and uploaded everything to extensions.gnome.org. Great to finally ship GNOME 40 support :)

**Comment by epileftro85** [comment]
Is this feature ready to just update package? I have re install and still no working :/ this same error
https://github.com/mlutfy/hidetopbar/issues/268#issuecomment-787093089
