### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by jefersonvinicius** [mlutfy/hidetopbar#269]
I have updated this extension and get this error

![Screenshot from 2021-03-02 07-56-20](https://user-images.githubusercontent.com/35340991/109638620-fab6e600-7b2c-11eb-8604-966712bd8207.png)

I'm already tried uninstall and install again and error persists.

Stack trace:
```
buildPrefsWidget/<@/home/jeferson/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/prefs.js:69:59
buildPrefsWidget@/home/jeferson/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/prefs.js:68:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by tuxor1337** [comment]
Which version of GNOME are you using?

**Comment by jefersonvinicius** [comment]
System: Ubuntu 20.04
GNOME Shell 3.36.4

**Comment by mnwstl** [comment]
I have the same problem with ubuntu 20.04 - GNOME 3.36.8. I removed the update and with the V28 returned to work.
With ubuntu 20.10 - GNOME 3.38.3, there were no problems.

**Comment by tuxor1337** [comment]
Yes, this only affects versions prior to 3.38. However, there's an easy fix for backwards compatibility.

**Comment by mnwstl** [comment]
I installed an earlier version (V28), but keeps asking to update. 
Ubuntu 20.04 is LTS and so it is not very comfortable...

**Comment by jefersonvinicius** [comment]
I did reinstall lasted extension version and now is woking on Ubuntu 20.04, Gnome 3.36.4

**Comment by mnwstl** [comment]
> I did reinstall lasted extension version and now is woking on Ubuntu 20.04, Gnome 3.36.4

How did you install it? I installed by command (sudo apt install gnome-shell-extension-autohidetopbar), but stayed in English and not in Portuguese BR as it was before. For now I'll keep the previous version.

**Comment by jefersonvinicius** [comment]
I install by gnome extensions site

**Comment by mnwstl** [comment]
> I install by gnome extensions site

Aqui não teve jeito e como uso pouco, optei por remover.

**Comment by mnwstl** [comment]
After the update, it was good! I take this opportunity to send a review of the Portuguese of Brazil - pt_BR. I ask to update in the source code. Thank you!

[locale.zip](https://github.com/mlutfy/hidetopbar/files/6103746/locale.zip)

**Comment by tuxor1337** [comment]
@mnwstl Thanks for the updated translation! It's included now. Maybe you can create a PR next time.
