### ISSUE TITLE
Stopped working on GNOME 3.32

### ISSUE THREAD

**Issue by David-Else** [mlutfy/hidetopbar#273]
Last time I installed from the gnome app store it worked, but now since I reinstalled Centos 8.3 from scratch it messes up the display and gives an error trying to change the settings. I have no other Gnome extensions installed.

See at the top, the top bar is not going away, the terminal is expanding upwards and leaving a tiny gap at the top. The error message comes when I try to change the settings from `tweaks`
![Screenshot from 2021-03-11 09-50-36](https://user-images.githubusercontent.com/12832280/110770631-731a5700-8251-11eb-876a-fb3739ac68f2.png)

Same effect here, the window expands up slightly instead of the top bar being removed.
![Screenshot from 2021-03-11 09-50-10](https://user-images.githubusercontent.com/12832280/110769364-018dd900-8250-11eb-8877-39ae8dc7d4ae.png)

I have tried installing the extension manually by downloading the different zips files of previous versions and replacing them in `~/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca`, but nothing seems to make it work. I tried ` gnome-shell-extension-tool -e hidetopbar@mathieu.bidon.ca` and ` gnome-shell-extension-tool -d hidetopbar@mathieu.bidon.ca
`

What has gone wrong? Are there now hidden settings somewhere in the system stopping previous versions working? Can I be sure it is totally uninstalled? Thanks!

Here it is off and on to clarify:
![Screenshot from 2021-03-11 10-01-39](https://user-images.githubusercontent.com/12832280/110770357-259dea00-8251-11eb-8bcb-264f90264d75.png)
![Screenshot from 2021-03-11 10-01-49](https://user-images.githubusercontent.com/12832280/110770358-26368080-8251-11eb-92f5-302e3a10e7d3.png)

Current JSON version coming from the gnome software is:
```json
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Hides the top bar, except in overview. However, there is an option to show the panel whenever the mouse pointer approaches the edge of the screen. And if \"intellihide\" is enabled, the panel only hides when a window takes the space.\n\n- Press backspace to remove keyboard shortcut.\n- Log off and on again when there is an error after upgrading.",
  "name": "Hide Top Bar",
  "settings-schema": "org.gnome.shell.extensions.hidetopbar",
  "shell-version": [
    "3.34",
    "3.32",
    "3.36",
    "3.38"
  ],
  "url": "https://github.com/mlutfy/hidetopbar",
  "uuid": "hidetopbar@mathieu.bidon.ca",
  "version": 88
```
It says `3.32` supported?

**Comment by tuxor1337** [comment]
Okay, we have to drop support for 3.32 apparently. Don't worry, you can still continue to use the old versions that worked for you.

You probably need to uninstall, log off, and install again. Furthermore, double-check that the extension settings are fine for your setup.

**Comment by David-Else** [comment]
@tuxor1337 Hi. I did as you said, and now Gnome Software has installed version 82.  I am afraid it does the exact same thing as the last version. I tried deleting / rebooting / reinstalling and even rebooting again.

Is it possible some settings are being remembered from the bad install, or maybe this new version is still just not compatible? I tried to install versions all the way back to `77` manually, and they kept on doing the same thing.
![Screenshot from 2021-03-11 14-23-15](https://user-images.githubusercontent.com/12832280/110801894-9656fd80-8275-11eb-8420-94db03b07019.png)


```
$ gnome-shell --version
GNOME Shell 3.32.2
```

**Comment by tuxor1337** [comment]
You can open the dconf-editor and remove all keys that contain `hidetopbar`. But all of this can be changed via the settings, as well, and the settings look okay according to your screenshot.

Maybe you can have a look at the error output in looking glass: Press Alt+F2, type in `lg` and press enter. Switch to the `Extensions` tab and look at `show errors` for the Hide Top Bar extension.

As a last resort, you can look at gnome-shell's log output using the command line `journalctl /usr/bin/gnome-shell -f -o cat`. Have it running in a terminal, deactivate and activate the extension, restart gnome-shell using Alt+F2 and `r` and see whether there are any log outputs related to hidetopbar.

**Comment by David-Else** [comment]
I had a go with `lg` and it said that the extension had not had any errors, but I have no idea what I am doing with the tool. 

This extension no longer says it is incompatible when you click the cog icon in tweaks. When you enable it, it simply pushes the window up as if there were no top bar, but the top bar remains hiding the top of the window.

Please could you open the issue again as it doesn't seem to work in `3.32`. Maybe if it works in another distros `3.32` it is something to do with a Centos/RHEL point release.

**Comment by tuxor1337** [comment]
Would you please create a new user account on your computer and install the extension on that account to make sure that this is really not about your setup being broken?

**Comment by David-Else** [comment]
I have done one better. I installed the Centos 8.3 ISO http://isoredirect.centos.org/centos/8/isos/x86_64/ in Gnome Boxes virtual machine and installed hidetopbar there without changing a thing, exact same bug! Note above the terminal menu bar there is still a small amount of the top of the window showing and the actual top bar has not moved:

![Screenshot from 2021-03-12 11-51-12](https://user-images.githubusercontent.com/12832280/110972296-beb52980-8353-11eb-8759-a629cbfb0de6.png)

I hope this can get sorted, I hate the wretched top bar wasting my screen space! This should be build into Gnome, it is just common sense to be able to get rid of the top bar.

**Comment by tuxor1337** [comment]
Okay, version 72 seems to be the last version working on 3.32. We probably should have dropped support for 3.32 together with 3.30, see #235. I deactivated all versions on extensions.gnome.org that erroneously claim to work with 3.32. So, after downgrading to 72 you should be fine.

**Comment by David-Else** [comment]
It works!!!!!!!!! Thanks :)
