### ISSUE TITLE
update/upgrade fails

### ISSUE THREAD

**Issue by Klystron** [mlutfy/hidetopbar#276]
My memory is a bit hazy but it's something like this; I keep getting a notification ( for months ) of a  hide top bar upgrade but when i follow the link and click the icon that i guess is for upgrade ( &*^@*!^)^!$# icons, , what happened to text,) it says 'failed' in red and the top bar doesn't hide. After much wwwing and many reboots I found alt-F2 r fixes it. Ubuntu 20.4.

**Comment by tuxor1337** [comment]
Duplicate of #242. Actually, there is a notice in the extension description on https://extensions.gnome.org/extension/545/hide-top-bar/
