### ISSUE TITLE
Most recent upgrade broke app

### ISSUE THREAD

**Issue by geektechniquestudios** [mlutfy/hidetopbar#277]
Installed on Ubuntu 20.04.2 via Gnome Shell Extensions. I updated today, and it immediately broke and stopped working. Uninstall and reinstall did nothing.

**Comment by DSkvorcov** [comment]
Ubuntu 20.10. the same problem

**Comment by tuxor1337** [comment]
This is most probably a duplicate of #242. (See also the notice in the extension description on https://extensions.gnome.org/extension/545/hide-top-bar/)

**Comment by geektechniquestudios** [comment]
> This is most probably a duplicate of #242. (See also the notice in the extension description on https://extensions.gnome.org/extension/545/hide-top-bar/)

Just to provide info on my issue, even if it is a duplicate: Logging out and back in did not repair the issue, nor did manually restarting the gnome-shell. After a fair amount of troubleshooting, I entirely uninstalled and reinstalled gnome-shell extensions to repair my issue.
