### ISSUE TITLE
hidetopbar doesn't work on Manjaro Gnome 40

### ISSUE THREAD

**Issue by GodGoldfish** [mlutfy/hidetopbar#279]
Hi everyone, 
The last update available on "https://extensions.gnome.org/extension/545/hide-top-bar/" doesn't work at all by showing an error on the "https://extensions.gnome.org/local/" page, i need to install (build) the version from github because otherwise it doesn't work.

---

MANJARO UP TO DATE
GNOME 40

**Comment by tuxor1337** [comment]
There is no official support for GNOME 40 in Hide Top Bar yet. Furthermore, compatibility with GNOME 40 is tracked in #268 already.
