### ISSUE TITLE
Disabling extension can crash shell

### ISSUE THREAD

**Issue by mrjohnson22** [mlutfy/hidetopbar#282]
Thank you for upgrading this extension to GNOME 40!

Unfortunately, with v92, it's possible to crash the shell by turning the extension off.

I'm able to consistently crash the shell by following these general steps:
1. Open GNOME Extensions and enable Hide Top Bar.
2. Fiddle with Hide Top Bar's settings. For example, flip some of the settings in Sensitivity.
3. Interact with the shell for a few minutes. For example, open/close the overview, hit the hot corner, press the cursor on the top of the screen to show the top bar, etc.
4. Go back to GNOME Extensions and disable Hide Top Bar.

I'm on Fedora 34 Workstation Edition. If it helps, here is the ABRT problem report that my system filed automatically: https://retrace.fedoraproject.org/faf/problems/bthash/?bth=1a80f6bd6fe0f2053dec9d9f2588ed2114d6d4f8&bth=a873815dc47cbc2754ae10e30608479309418f09

**Comment by GodGoldfish** [comment]
+1
