### ISSUE TITLE
topbar overlay with the overview's search bar

### ISSUE THREAD

**Issue by vikashraghavan** [mlutfy/hidetopbar#283]
i'm running on fedora 34 on x11

topbar overlay with the overview's search bar until there is an event

Steps to reproduce:
goto overview

![Screenshot from 2021-05-04 10-39-23](https://user-images.githubusercontent.com/48412820/116963189-c050fd00-acc5-11eb-9111-82f8b8feb5d9.png)

**Comment by vikashraghavan** [comment]
the temporary fix could be setting the slide animation time on overview to 0

but if we want the animation on overview it's not working

**Comment by loulou921222** [comment]
it does this when the animation time is set to 0.3 or higher. 0.1 and 0.2 work but the animation for 0.2 looks janky

**Comment by vikashraghavan** [comment]
And, while exiting the overview, the dock gets enlarged. a fix to prevent it would be better!

**Comment by vikashraghavan** [comment]
Now, time < 0.2 is also not working

**Comment by molitona** [comment]
@tuxor1337 
https://github.com/mlutfy/hidetopbar/issues/295

**Comment by ljhui** [comment]
is there any progress? it's so annoying.

**Comment by vikashraghavan** [comment]
A temporary fix would be using just perfection  
1. Check show in overview (In hide top bar)
2. decrease the icon size (In Just perfection)
3. Hide search bar (In Just perfection)
4. And move the centre clock widget to left or right (In Just perfection)

Finally it looks like this
![image](https://user-images.githubusercontent.com/48412820/132114855-d571437f-d3b0-4f8c-8c3e-fbe537b081e3.png)

**Comment by tuxor1337** [comment]
@vikashraghavan Thanks for the workaround!

This is very hard to approach due to the way the allocation happens in `ControlsManagerLayout`, as pointed out by @3v1n0 in https://github.com/mlutfy/hidetopbar/issues/284#issuecomment-875210142

A solution would probably require non-trivial changes to parts of the UI that we haven't touched so far: e.g. the search entry or the controls manager. Feel free to create a PR if you find an elegant solution.

**Comment by lbrfabio** [comment]
Another workaround is to put a file called **stylesheet.css** inside the **hidetopbar@mathieu.bidon.ca** folder with this rule:

`.search-entry {
  margin-top: 36px;
}`

The original margin of the search bar depends on the theme used.  
In my case I use Arc that has a 10px margin so I added 26px of the panel.  
In gnome default theme Adwaita I think it's 30 so you can put a 56px margin but 36px works too

**Comment by molitona** [comment]
worked thanks.

**Comment by aunetx** [comment]
I created #299 which should entirely fix this issue, and BTW I added an option in [Blur my Shell](https://extensions.gnome.org/extension/3193/blur-my-shell/) to be compatible with Hide Top Bar (that's no advertising, I swear ;p)
