### ISSUE TITLE
Janky Animations in Gnome 40

### ISSUE THREAD

**Issue by SP1966** [mlutfy/hidetopbar#284]
Rather than try to explain it, here's a video:

https://youtu.be/C_jNm7gBPmY

While in Activities view if you switch to another workspace that has the Topbar in view from one that does not it looks terrible when the Topbar animates in. Not sure what if anything can be done, just thought I'd share. 

Thanks for the excellent extension!

**Comment by tuxor1337** [comment]
Maybe I leave this open for future users that feel the same. To me, it doesn't feel that bad and it's probably quite hard to "fix".

**Comment by foundObjects** [comment]
I just came to report the same thing, you can also trigger it by entering the overview with the top bar hidden and then mousing over any window inside the overview container -- the top bar pops into view and the whole overview screen "jumps" (for lack of a better description) into place. 

Is it possible to detect entering the overview and suspend hiding the top bar until the user leaves?

**Comment by tuxor1337** [comment]
By the way, are you using the preference "Show panel in overview"? If yes (i.e., the setting is active), this is a bug. If not (i.e., the settings is inactive), would you generally prefer to have the panel stay hidden while in overview?

**Comment by tuxor1337** [comment]
Would one of you please check whether commit 285d953c2bb0123cfddde37a877e7ae09c88fb2e fixes this for you?

**Comment by SP1966** [comment]
> Would some of you please check whether commit [285d953](https://github.com/mlutfy/hidetopbar/commit/285d953c2bb0123cfddde37a877e7ae09c88fb2e) fixes this for you?

Not sure how to do that, but I did just get an update to version 93 so I'm not sure if that is in there. 

> By the way, are you using the preference "Show panel in overview"? If yes (i.e., the setting is active), this is a bug. If not (i.e., the settings is inactive), would you generally prefer to have the panel stay hidden while in overview?

My personal preference would be to show it in the overview, but it's not a deal breaker by any means. I guess I'm just too uptight about this, it just feels unfinished/polished when the topbar comes into view and everything adjusts. If I turn off "Only hide panel when a window takes this space" it all works fine, but then I don't like having to mouse over to view the panel! 

None of this is a deal breaker, if there is a way to smooth out the animations that'd be great, if not I'll survive! Thanks for your attention on this minor issue!

**Comment by 3v1n0** [comment]
This is related to the way the allocation happens in `ControlsManagerLayout`.

It should be adapted as it happens in https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1892 (or patched as we do in dash-to-dock https://github.com/micheleg/dash-to-dock/pull/1402).

**Comment by tuxor1337** [comment]
Having used GNOME 40 for a while now, I think that this issue is actually fixed or covered by #283
