### ISSUE TITLE
What if I want it gone completely?

### ISSUE THREAD

**Issue by rbreaves** [mlutfy/hidetopbar#285]
Not exactly a bug - but I have noticed it will come back in my VM if I resize the window and that is highly annoying. I want it gone completely because I am actually running and using xfce4-panel instead.

**Comment by tuxor1337** [comment]
Did you try deactivating the preference "Only hide when window takes the space"?

**Comment by rbreaves** [comment]
I found Just Perfection does what I actually want. It disables it completely.
