### ISSUE TITLE
Can't bind shortcut on Fedora 34 Gnome 40 Wayland

### ISSUE THREAD

**Issue by zheneknew** [mlutfy/hidetopbar#287]
I'm trying to bind Super+Esc on "Key that triggers the bar to be shown" but it seems like it doesn't try to catch my keys in some cases, and it shows me "Invalid" in other cases. 
The maximum that I have achieved - turn off the extension, then it allows me bind "Ctrl+Shift+\<AnyLetterKey\>", but still does not allow Super+Esc.
Could you please tell me where config file is, in which I can write shortcut that I need manually?

**Comment by tuxor1337** [comment]
Setting Super+Esc is not possible, because that is already a default shortcut: https://askubuntu.com/questions/1263254/cant-create-keyboard-shortcuts-utilizing-the-esc-key

**Comment by NicTanghe** [comment]
i have tried every key combo on my keyboard with 36 neverything returns invalid

**Comment by tuxor1337** [comment]
@NicTanghe That's a different bug #336
