### ISSUE TITLE
No JS module tweener found

### ISSUE THREAD

**Issue by chrisolsen** [mlutfy/hidetopbar#298]
The extension doesn't work for me on a fresh install of Zorin 16.
![image](https://user-images.githubusercontent.com/41582/132235388-d9aad0dc-4397-44e5-8e68-247b28151487.png)

**Comment by tuxor1337** [comment]
My guess would be, that you are using an outdated version of this extension. How did you install it?

**Comment by chrisolsen** [comment]
I installed it with the `sudo apt install gnome-shell-extension-autohidetopbar` command shown in the README
![image](https://user-images.githubusercontent.com/41582/132258451-c46ae646-ee31-4f7d-85fc-92036ce2319b.png)

Since it seems like that version was made over a year ago, I tried to install it from the Gnome extensions site, which installed version 93, but I am still getting the same issue

![image](https://user-images.githubusercontent.com/41582/132258752-930be681-a59a-4a11-9a27-dd1b201eb8dc.png)

**Comment by tuxor1337** [comment]
@coldtobi Do you happen to know why `gnome-shell-extension-autohidetopbar` is outdated and what we can do about that?

Did you log off and on after installing from the extensions.gnome.org?

**Comment by chrisolsen** [comment]
After ensuring it was uninstalled and reinstalling via the browser I was able to get it installed with it showing up in the "manual installation" section and things worked, but it still shows up as version 93..just this time it works.
