### ISSUE TITLE
Extension not loading

### ISSUE THREAD

**Issue by gapop** [mlutfy/hidetopbar#301]
After upgrade to version 94 the extension doesn’t load anymore. The error message is: “_searchEntryBin is undefined”. Ubuntu 21.04 64-bit, Gnome 3.38.5, X11.

**Comment by ebrattli** [comment]
I just got the same error after updating the extension. Pop!_OS 21.04 Gnome 3.38.4.

**Comment by mhoangvslev** [comment]
I traced it back to [this line](https://github.com/mlutfy/hidetopbar/blob/master/panelVisibilityManager.js#L309)

**Comment by mhoangvslev** [comment]
I also think that the latest update is intended for GNOME 40 but somehow the 3.38 users got it as well.

**Comment by mhoangvslev** [comment]
It's still there
