### ISSUE TITLE
Doesn't work on Ubuntu 20.04 with Gnome 3.38 with latest version

### ISSUE THREAD

**Issue by RudRecciah** [mlutfy/hidetopbar#309]
I updated this today, and have no idea why it won't work. Gnome extensions just says there's an error when I try to install it. If there's any logs somewhere that I should send let me know!

**Comment by coldtobi** [comment]
Did you try the Ubuntu/Debian packaged version? https://launchpad.net/ubuntu/+source/gnome-shell-extension-autohidetopbar resp. https://tracker.debian.org/pkg/gnome-shell-extension-autohidetopbar ?

**Comment by RudRecciah** [comment]
that worked for me, thanks!
