### ISSUE TITLE
Gnome 41 compatibility

### ISSUE THREAD

**Issue by lakotamm** [mlutfy/hidetopbar#311]
Hello! I can see that there is no version for Gnome 41 on the [Gnome Shell Extension website](https://extensions.gnome.org/). Is there any plan to introduce it?

Thank you!

**Comment by tuxor1337** [comment]
You are welcome to test this extension on GNOME 41 and report your experiences. If everything works as expected, I will be happy to add 41 to the supported versions. If there are new issues, you are welcome to propose your fixes.

**Comment by lakotamm** [comment]
So I manually installed the version from Gnome shell extension website for Gnome 40. I had to add version "41" to metadata.json and all seems fine.

I am running it on the latest Fedora 35 Silverblue.

**Comment by tuxor1337** [comment]
Thanks for testing! I added 41 to the list of supported versions :)

**Comment by lakotamm** [comment]
I can confirm that the new version works without modifications. Just an info for someone else with Fedora 35 - I again had to install it manually (there is some bug with the web install atm).
