### ISSUE TITLE
Enable toggle top-bar on shortcut - and a toggle speed bug

### ISSUE THREAD

**Issue by jacksongoode** [mlutfy/hidetopbar#316]
As of now the ability to toggle the top-bar only allows a delay before it disappears. It would be a great feature to allow the toggle to exist until the shortcut is pressed again (note: this wouldn't readjust the windows, the top-bar would still act as an overlay).

There is also a bug that exists with the current implementation. The delay that's chosen in the "Keyboard Shortcuts" tab actually alters the speed at which the top bar appears when the shortcut is triggered as well as it's duration in remaining there. The speed for entering should respect the value that is set in "Animation".

**Comment by tuxor1337** [comment]
There already is an option "Pressing the shortcut again rehides the panel".

The animation times are only for

* when entering/leaving overview,
* when mouse approaches edge of the screen.

As mentioned in the description of those preferences

**Comment by jacksongoode** [comment]
> There already is an option "Pressing the shortcut again rehides the panel".
> 
> The animation times are only for
> 
>     * when entering/leaving overview,
> 
>     * when mouse approaches edge of the screen.
> 
> 
> As mentioned in the description of those preferences.
> 
> The animation time when pressing the shortcut must be dependent on the "delay before the bar rehides" to make sure that the panel is shown in full for a sufficient amount of time in cases where the delay is very short.

Ok, I can see the rational where the delay time may be less than the "Slide animation time when entering/exiting" then it makes sense to be dependent on a fraction of "Delay before the bar rehides". It just seems a little strange for the exiting animation to be short while the entering animation when pressing the shortcut could be very long (in the case where the "delay" setting is 10s). My suggestion would be that a keypress should drop the panel at a relatively fast speed (the same as the existing speed) when the time is long enough (some threshold).

For the "Pressing the shortcut again rehides the panel", I would have thought there might be an option where the delay time would be infinite when this is enabled. For example, another toggle above the delay time called "Enable delay for bar to re-hide" where this would be on by default, allowing a delay to be set, but if one toggled it off the delay time would grey out and it would be on until the user pressed the shortcut again.

**Comment by tuxor1337** [comment]
The delay time is infinite if you set the delay to 0.  I now mention this feature in the preferences dialog. Furthermore, in case of very long delay times, I made sure that the show animation time will not exceed the animation time for when the mouse approaches the edge of the screen.

Does this solve your issue?

**Comment by jacksongoode** [comment]
Oh that works nicely, thanks!
