### ISSUE TITLE
Compatibility with Ubuntu Impish Indri

### ISSUE THREAD

**Issue by cazacugmihai** [mlutfy/hidetopbar#317]
Please make this extension to be compatible with Ubuntu Impish Indri (having GNOME 40.5).

**Comment by cazacugmihai** [comment]
I've created another user on my system and, by using it, it seems that the extension is already working with Ubuntu 21.10. 
Is there a way to reset everything regarding these gnome extensions, for my account?
Thank you!

**Comment by tuxor1337** [comment]
Hey @coldtobi, can you help @cazacugmihai with his Ubuntu setup: they would like to "reset everything regarding these gnome extensions, for my account"?

**Comment by cazacugmihai** [comment]
I have removed all my gnome settings by running `dconf reset -f /org/gnome/` and deleting the `~/.local/share/gnome-shell/extensions` folder. Everything works fine now. Thank you!
