### ISSUE TITLE
Control panel not showing on ubuntu 21.10

### ISSUE THREAD

**Issue by kazielcamacho** [mlutfy/hidetopbar#320]
Control panel not showing on ubuntu 21.10, it shows the following error:
GLib.FileError: Falló al abrir el archivo «/usr/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/Settings-40.ui»: No existe el archivo o el directorio

Stack trace:
  buildPrefsWidget@/usr/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/prefs.js:44:13
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by tuxor1337** [comment]
@coldtobi Is this a problem with the official Ubuntu package?

**Comment by coldtobi** [comment]
Yes, this is a packaging bug... https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=995756
Fixed in Debian unstable already, though it might take time until Ubuntu picks it up...

**Comment by prateekj117** [comment]
Ahh, facing this too.

**Comment by MohammadMD1383** [comment]
> For now, I just manually created the file and it works now !!! Thanks.

Well ... could you please tell us which file and where? Thanks :)

**Comment by zouharvi** [comment]
The `Settings-40.ui` file is in this repository. Just downloading it and putting it where it belongs fixed the issue for me. (yeah I know that curling to protected dirs is dangerous)

```
sudo su
curl https://raw.githubusercontent.com/mlutfy/hidetopbar/master/Settings-40.ui > /usr/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/Settings-40.ui
```

**Comment by MohammadMD1383** [comment]
> The `Settings-40.ui` file is in this repository. Just downloading it and putting it where it belongs fixed the issue for me. (yeah I know that curling to protected dirs is dangerous)
> 
> ```
> sudo su
> curl https://raw.githubusercontent.com/mlutfy/hidetopbar/master/Settings-40.ui > /usr/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/Settings-40.ui
> ```

Thanks! It works now!

**Comment by coldtobi** [comment]
FWIIW: The Debian package version 20211001-1 fixes this issue. Ubuntu "The Jammy Jellyfish" has the fix already, for the older release (which ships Gnome 40), you should be able to download the deb from here [1] and simply install it (as the deb has almost no external dependencies, this will work.)

[1] https://launchpad.net/ubuntu/+source/gnome-shell-extension-autohidetopbar

**Comment by WhiteCzar** [comment]
Still not working:

The settings of extension hidetopbar@mathieu.bidon.ca had an error:
```
GLib.FileError: Failed to open file “/usr/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/Settings-40.ui”: No such file or directory
```

Stack trace:
```
buildPrefsWidget@/usr/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/prefs.js:44:13
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
Ubuntu 21.10

**Comment by coldtobi** [comment]
Please let me know  the output of:
`dpkg -l gnome-shell-extension-autohidetopbar`

Thanks

**Comment by WhiteCzar** [comment]
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                 Version      Architecture Description
+++-====================================-============-============-==================================
ii  gnome-shell-extension-autohidetopbar 20210525-2   all          GNOME shell automatic topbar hider

Thank you!

**Comment by coldtobi** [comment]
> ```
> ii  gnome-shell-extension-autohidetopbar 20210525-2   all          GNOME shell automatic topbar hider
> ```

@WhiteCzar Your package is "too old". You need at least `20211001-1`

Your options: 
- Try a `apt update; apt upgrade `
- If that does not bring the new version, you should file a bug at Ubuntu. (so that they will fix it.) 

Until then, your options are to locally install the deb: Use the instructions from https://github.com/mlutfy/hidetopbar/issues/320#issuecomment-987835452

**Comment by WhiteCzar** [comment]
@coldtobi Oh I get it. Yeah Ubuntu always ships packages that are a few months old. Thank you very much!
