### ISSUE TITLE
Hiding won't work on Gnome 41 with Fedora 35.

### ISSUE THREAD

**Issue by jeffbuhrt** [mlutfy/hidetopbar#324]
I switched to Fedora 35 and confirmed the OS and the hidetopbar extension is up to date via: https://extensions.gnome.org/local/

gnome-desktop3-41.1-1.fc35.x86_64
chrome-gnome-shell-10.1-14.fc35.x86_64

Any hints or things to try/test? [I do development.]

Thanks,

-Jeff

**Comment by tuxor1337** [comment]
It reportedly used to work on Fedora 35 with Gnome 41: https://github.com/mlutfy/hidetopbar/issues/311 However, the used mentioned a problem with the web install.

**Comment by jeffbuhrt** [comment]
This seems to be fine now: gnome-shell-41.1-1.fc35.x86_64 (so one of a list of other packages must have done it). One more thing to try is bring up the new 'Extensions' app, turn off and back on all extensions, then do the same with Hide Top Bar.
