### ISSUE TITLE
Fill Preferences Window gnome 42 Ubuntu 22.04 Jammy

### ISSUE THREAD

**Issue by rmkimathi** [mlutfy/hidetopbar#349]
The settings window does not expand to fit while using gnome-shell-extension-prefs. Ubuntu 22.04, gnome 42.beta

![Screenshot from 2022-03-19 05-34-55](https://user-images.githubusercontent.com/13484308/159103700-ec058a8b-aa48-40cc-8df1-6ed8e449aac6.png)

**Comment by nikeshocks65** [comment]
Can replicate - Fedora Silverblue 36 Beta - gnome 42.beta
