### ISSUE TITLE
Extension crashed when installed from https://extensions.gnome.org/extension/545/hide-top-bar/

### ISSUE THREAD

**Issue by Microwave-WYB** [mlutfy/hidetopbar#352]
I think the compiled schemas is not working. Got the schemas not found error when installed from the website. A possible fix could be pushing the compiled schemas to the repo.

**Comment by tuxor1337** [comment]
Thanks for reporting this! Indeed, I accidentally included the wrong gschemas.compiled binary file in version 105. This is fixed in Version 106 (which should be available any moment).

**Comment by Microwave-WYB** [comment]
NVM worked after reinstall
