### ISSUE TITLE
Intelihide doesn't work properly on dual monitor

### ISSUE THREAD

**Issue by HideyoshiNakazone** [mlutfy/hidetopbar#359]
When using two monitors and _**Only hide panel when a window takes the space**_ option is enabled the extension doesn't detect a window in the other monitor and therefore the top bar never hides, even if there is a window in the main monitor. 
I ask for the implementation of a feature that ignores the second monitor since the top bar doesn't extends to it.

Love the extension and thanks for all the hard work!

**Comment by tuxor1337** [comment]
Isn't this a duplicate of #136?

**Comment by HideyoshiNakazone** [comment]
I don't know, all i know is that the top bar won't show in my empty primary monitor if there is a window in my second monitor

**Comment by HideyoshiNakazone** [comment]
Recents Updates Fixed the Issue so i'm closing this issue. Thank you very much!
