### ISSUE TITLE
Extension error in openSUSE Leap. 

### ISSUE THREAD

**Issue by asurraco** [mlutfy/hidetopbar#363]
NAME="openSUSE Leap"
VERSION="15.3"

```
2022-05-12T19:49:40.340150-03:00 Sineriz-pos-2-01 gnome-shell[2287]: 
JS ERROR: Extension hidetopbar@mathieu.bidon.ca: 
TypeError: Main.overview._overview._controls is undefined
#012@/home/user/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/panelVisibilityManager.js:36:7
#012@/home/user/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/extension.js:25:7
#012_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:343:13
#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:277:22
#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:490:13
#012collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
#012_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:469:9
#012_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:499:13
#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:530:13
#012init@resource:///org/gnome/shell/ui/extensionSystem.js:48:9
#012_initializeUI@resource:///org/gnome/shell/ui/main.js:242:5
#012start@resource:///org/gnome/shell/ui/main.js:138:5
#012@<main>:1:31
```

**Comment by tuxor1337** [comment]
Please provide information about your setup:
0. X11 or Wayland
1. Version of GNOME.
2. Version of Hide Top Bar.
3. Your Hide Top Bar settings.
4. Extensions running in parallel.
5. Number of monitors.

If you have other extensions running in parallel, please try to reproduce the issue with all other extensions deactivated.

Please provie step-by-step instructions on how to reproduce the issue.

**Comment by asurraco** [comment]
Thanks for your reply.

1- X11
2 - GNOME Shell 3.34.5
3 -  Version 100
4 -  It still has the default settings since I can't activate it from the GNOME Tweaks tool
5 - There is no other extension running in parallel
6 - One monitor

Regards

**Comment by tuxor1337** [comment]
I'm sorry, but we dropped support for 3.34 long time ago, so this won't be fixed.

**Comment by asurraco** [comment]
hi @tuxor1337  Could you tell me how I could install an older version of this extension? Download version 68 of the extension but I can't find anywhere that indicates how to install it.

**Comment by tuxor1337** [comment]
I can't guarantee that an older version of the extension will work for you. Last thing I know was that version 100 was supposed to work on 3.34. To install an older version, unzip it as a subdirectory in `$HOME/.local/share/gnome-shell/extensions/` called `hidetopbar@mathieu.bidon.ca` and run `gnome-extensions enable hidetopbar@mathieu.bidon.ca`.

**Comment by asurraco** [comment]
Tks @tuxor1337 regards!!!
