### ISSUE TITLE
Add shortcut to stop the autohide

### ISSUE THREAD

**Issue by antoniofsm** [mlutfy/hidetopbar#366]
A shortcut to stop/start the extension would be useful to show the topbar fixed temporally without deactivating/reactivating the extension. As the actual Super+Q but deactivating the autohide feature (maybe Super+Caps+Q).

**Comment by tuxor1337** [comment]
How is this different from deactivating the extension? Why don't you just add a system shortcut to toggle the extension enabled state?

**Comment by antoniofsm** [comment]
> Why don't you just add a system shortcut to toggle the extension enabled state?

Yep, thank you for the tip. I didn't know the command `gnome-extensions disable/enable`, found due to your comment.

I've solved it by assigning shortcuts for `gnome-extensions disable hidetopbar@mathieu.bidon.ca` and `gnome-extensions enable hidetopbar@mathieu.bidon.ca`

However, including the feature in the extension options UI might still be helpful for less experienced users.
