### ISSUE TITLE
Can't see top panel in overview mode when using dual monitors

### ISSUE THREAD

**Issue by joshuaMarple** [mlutfy/hidetopbar#47]
When in overview mode, the top panel is not visible when using dual monitors where the primary monitor is smaller than the secondary monitor. Switching the primary monitor to the larger monitor resolves this issue.

**Comment by tuxor1337** [comment]
Fixed in latest version (now in review queue at extensions.gnome.org).

**Comment by trunneml** [comment]
Works for me now, Thanks a lot!
