### ISSUE TITLE
GNOME 3.16 support

### ISSUE THREAD

**Issue by alienhjy** [mlutfy/hidetopbar#61]
Don't work on gnome-shell 3.16, even if add "3.16" on metadata.json. Please try to fix it, thx.

**Comment by tuxor1337** [comment]
I won't be updating to 3.16 before end of May... But maybe somebody else can help you with this :)

**Comment by alienhjy** [comment]
@tuxor1337 OK, got it. Thanks for your work.

**Comment by omyno** [comment]
@alienhjy This only requires a small change in topPanel.js: https://github.com/omyno/hidetopbar/commit/5af6ffc03bb8c65ceb810007f0a62847bf076f02.

**Comment by alienhjy** [comment]
@omyno It work partially, thx. But it still has problem with "Intellihide".

**Comment by tuxor1337** [comment]
Thanks, omyno!

The intellihide code is taken from https://github.com/micheleg/dash-to-dock. They recently introduced major changes to their intellihide code and their code is compatible with 3.16. Still, I think adapting our code to fit their changes is doable. I can't work on this at the moment. So feel free to take and work on it. If I decide to work on this, I will announce it here.

**Comment by tuxor1337** [comment]
I just started working on this and unfortunately, the intellihide-option "only when the active window takes the space" seems to break with GNOME 3.16, but the intellihide-behaviour itself works very well.
