### ISSUE TITLE
Broken since last update on 3.14

### ISSUE THREAD

**Issue by jljouannic** [mlutfy/hidetopbar#66]
When installing the extension, the `ON/OFF` switch turns red and shows `ERROR`.

The Looking Glass console shows the following error message:

```javascript
Shell.ActionMode is undefined
```

**Comment by tuxor1337** [comment]
That is ... strange, to say the least. Nothing regarding `Shell.ActionMode` has been changed in the curse of the update. I will run in a VM and test it ;)

**Comment by jljouannic** [comment]
That was fast! Thanks!
