### ISSUE TITLE
Broken (again) since last update on 3.14 

### ISSUE THREAD

**Issue by jljouannic** [mlutfy/hidetopbar#67]
Does not work when installed from https://extensions.gnome.org/ (shows ERROR instead of ON/OFF switch).

Works fine when installed manually by cloning repository as indicated in README.

**Comment by tuxor1337** [comment]
Oh, it's very good, that you mention this. I made an embarrassing mistake while packaging, don't ask for more details *facepalm*

I deactivated v41 and v42 is awaiting review.
