### ISSUE TITLE
Hide hidden bar from monitor above panel?

### ISSUE THREAD

**Issue by GNOMES** [mlutfy/hidetopbar#68]
With a monitor attached above my screen, I can see the bar when it is in its hidden state on the bottom of the monitor above it. Any ideas to remedy?
![screenshot from 2015-05-26 17-29-48](https://cloud.githubusercontent.com/assets/7462046/7824948/1fc9a4f6-03cd-11e5-9d7f-20e9a9a96e42.png)

**Comment by tuxor1337** [comment]
The bar should only be shown for a fraction of a second, like in this screencast: http://tovotu.de/data/hidebad.webm

Would you please list all simultaneously running extensions as well as the settings that you use with Hide Top Bar? What is the GNOME version you are using?

**Comment by GNOMES** [comment]
gnome-shell 3.16.2-2
![screenshot from 2015-05-27 08-18-18](https://cloud.githubusercontent.com/assets/7462046/7836837/fab4a414-0448-11e5-893b-addf2450efb5.png)

Here you can see better what I am talking about. I you can see my monitor arrangement in the photo, I am unable to move my top monitor closer, a black bar is between them in photo. If I disable your extension, I am able to move the monitor closer. I am guessing your hiding the top bar by moving it off screen, rather then truly hiding it? Any way to 100% remove it except in overview? 

Also I put the chrome window to show that it is at the bottom of my small monitor, and 100% above my bottom right screen. In your screencast it stays on bottom, but you also have it do the intellehide feature which I do not use, and did not help when I just tried it.

I only use your extension and user theme extension, disabling user theme, plus alt + f2, then r, does not resolve the issue. 
![screenshot from 2015-05-27 08-24-38](https://cloud.githubusercontent.com/assets/7462046/7836965/e528af9a-0449-11e5-9b7a-2aa34be3a2a0.png)

in this second screenshot you can see that I moved the top monitor to the left a bit, and you can see the top bar is still located above the bottom screen, and is still showing on top. This is my desired main screen... I am willing to switch if this cannot be figured out.

**Comment by tuxor1337** [comment]
I'm also on GNOME 3.16.2 and I can't reproduce this. Would you please show a screenshot of the extension's settings? Make sure to deactivate all mouse-sensitivity related settings.

**Comment by tuxor1337** [comment]
Okay, you seem to use mouse-sensitivity related settings even though I always thought that this wouldn't make sense in such a monitor setup... I have a patch for you. Just wait a few hours ;-)

**Comment by GNOMES** [comment]
What ever you did, it works great now!
