### ISSUE TITLE
Going in overview mode skips animation

### ISSUE THREAD

**Issue by LaurentTreguier** [mlutfy/hidetopbar#69]
Since the last update of the extension, when going in the activities overview with focus on a fullscreen window, the animation leading to the windows thumbnails always gets skipped. It only started happening right after the update. I'm using Archlinux (up-to-date) with Gnome 3.16.2. I tried disabling every other extension, re-installing autohide-topbar and restarting the session, with no success.
It's no big deal, but I find it strange. Is there anything that could relate to this in the recently changed code ?

**Comment by tuxor1337** [comment]
I can't reproduce this. Would you please post your settings?

**Comment by LaurentTreguier** [comment]
Yes, I meant the window animation ; I should have been more precise in my description.

**Comment by LaurentTreguier** [comment]
I can confirm it's back to normal now. Thank you !
