### ISSUE TITLE
Optionally hide/show on shortcut press only

### ISSUE THREAD

**Issue by andreicristianpetcu** [mlutfy/hidetopbar#70]
Hello, 

Please offer option to disable autohide. I want to show the topbar and hide it on demand with a keyboard shortcut (Super+T). I do not want it to autohide itself or appear when I move the mouse next to it.

Thank you!

**Comment by tuxor1337** [comment]
On pressing that shortcut, do you want to hide the bar forever or for a certain period of time or until the shortcut is pressed again? What is the exact usecase of this?

**Comment by andreicristianpetcu** [comment]
After I press the shortcut I want the bar to stay hidden until I press again, if I press the shortcut and it appears, I want it to stay visible until I hit the shortcut again. Right now, if it is visible and a window overlaps it, it dissapears.

**Comment by tuxor1337** [comment]
Okay, that feature request sounds feasible.

**Comment by andreicristianpetcu** [comment]
Thank you!

**Comment by tuxor1337** [comment]
Do you want the top bar to overlap maximized windows whenever it is shown? Because, currently, that is the default behavior. If you don't want the top bar to overlap any windows, I don't think it makes sense to implement this as a behaviour of this extension. Instead, you should configure a GNOME shortcut for disabling/enabling this extension.

**Comment by andreicristianpetcu** [comment]
Hmmmm.... I will try that. Thank you!

**Comment by andreicristianpetcu** [comment]
Sorry, I tried from CLI but it does not work

```bash
$gnome-shell-extension-tool -e hidetopbar  
'hidetopbar' is now enabled.
$gnome-shell-extension-tool -d hidetopbar
'hidetopbar' is now disabled.
```
It only prints the message, it does not enable/disable the extension.

**Comment by tuxor1337** [comment]
The CLI is a bit buggy, unfortunately. Sometimes it doesn't do what it should do. Namely, it should edit the gsettings entry `enabled-extensions` in `org.gnome.shell`. You can easily check that with `gsettings get org.gnome.shell enabled-extensions`. If you repeatedly execute the gnome-shell-extension-tool it usually works eventually...

**Comment by andreicristianpetcu** [comment]
Pffff.... I was using it wrong :) Thank you!

```bash
gnome-shell-extension-tool -e hidetopbar@mathieu.bidon.ca
gnome-shell-extension-tool -d hidetopbar@mathieu.bidon.ca
```

**Comment by andreicristianpetcu** [comment]
```bash
$gnome-shell-extension-tool -e hidetopbar@mathieu.bidon.ca || gnome-shell-extension-tool -d hidetopbar@mathieu.bidon.ca
```
