### ISSUE TITLE
Bottompanel compatibility?

### ISSUE THREAD

**Issue by Barthalion** [mlutfy/hidetopbar#72]
If the bar has been moved to the bottom of screen with Bottompanel extension, user still has to move cursor to the upper edge of screen to trigger panel's visibility. Could said edge be configurable?

**Comment by dffischer** [comment]
I absolutely support this proposal. With the autohiding bar moved to the bottom, I can finally also autohide my Firefox tabs at the top.

I forked and tried to tinker a bit with this in [a branch named `bottompanel` in my fork](https://github.com/dffischer/hidetopbar/tree/bottompanel). I managed to get the pressure barrier and animation right, making the panel appear correctly at the bottom. Unfortunately, it disappears again when the mouse touches or leaves any of the elements on the panel (e.g. the clock). Perhaps @tuxor1337 has an idea whether they need to be treated specially in any way.

If you want to experiment with the branch, be aware that it will not work without Bottompanel also active. I plan to add configuration and create a pull request as soon as all the details are figured out.

**Comment by tuxor1337** [comment]
Hm, I think supporting the change of orientation is a mess, especially in a multi monitor setup. Furthermore, enabling the BottomPanel extension while the panel is hidden will result in a wrong anchor point because the panel height is changed by Hide Top Bar.

However, if you are interested in what I tried so far, feel free to look at the bottompanel branch that I just created: https://github.com/mlutfy/hidetopbar/tree/bottompanel

**Comment by dffischer** [comment]
It works quite fine not even showing the problem I described in my last comment. The is just one caveat: I still have to touch the _upper_ edge of the screen to make the panel appear at the _bottom_.

**Comment by tuxor1337** [comment]
I created a pull request for BottomPanel that should bring multi-monitor support: https://github.com/Thoma5/gnome-shell-extension-bottompanel/pull/1
Furthermore, I will close this issue in a minute with the next commit ...

**Comment by dffischer** [comment]
The first time directly after activation, the bar may roll out in the wrong direction, but after that, everything works fine. Thank you for the fix.

**Comment by peter-kehl** [comment]
Hi Thomas @tuxor1337,

Thank you for the pull request for Bottom Panel. Unfortunately, it doesn't work for very long. (https://github.com/Thoma5/gnome-shell-extension-bottompanel/issues/12)

Any ideas, please?
