### ISSUE TITLE
Bar not hiding on screen unlock and GDM startup

### ISSUE THREAD

**Issue by latot** [mlutfy/hidetopbar#76]
Hi again, here a little bugs, when you unlock the screen the top bar not hidding. and this happend some times when gdm start, the top bar not hidding.

Thx, Cya

**Comment by tuxor1337** [comment]
I can't reproduce this. Would you specify which version of GNOME you are using, which extensions you use in parallel and what your hidetopbar settings are, please?

**Comment by mattdm** [comment]
I get this too with GNOME 3.16.3 in Fedora 22, very reliably. Going to the overview once and then returning hides the bar again, so it's not annoying enough that I bothered to report. This started happening when you fixed the [previous bug, where it wasn't _appearing_ after screen lock](https://github.com/mlutfy/hidetopbar/issues/58).

![screenshot from 2015-09-10 08-35-22](https://cloud.githubusercontent.com/assets/123367/9788317/eb2df792-5796-11e5-902f-553c5acc5c23.png)

I have a bunch of other extensions - activities configurator, alternate tab, always zoom workspaces, autohide battery, caffeine, dash to dock, impatience, native window placement, and topicons. I'll try disabling the others to see if I can still reproduce.

**Comment by mattdm** [comment]
awesome -- thanks!
