### ISSUE TITLE
Disable "show bar" trigger shortcut 

### ISSUE THREAD

**Issue by Ritmxoid** [mlutfy/hidetopbar#77]
Once "key that trigger the bar to be shown" option is set there is no obvious way to disable it. Couldn't find how to delete shortcut.

**Comment by tuxor1337** [comment]
Same as in gnome control-center: Press backspace to delete shortcut.

**Comment by peter-kehl** [comment]
Dear Thomas @tuxor1337,

Thank you for improving and shepherding Hide Top Bar.

May I suggest you add a note like "To clear the shortcut, press backspace" to the settings, or to README.md and/or to https://extensions.gnome.org/extension/545/hide-top-bar, please.
