### ISSUE TITLE
i'd like to be able to enable/disable this wonderfull extension from the terminal

### ISSUE THREAD

**Issue by maxwellzdeamon** [mlutfy/hidetopbar#78]
This extension is a huge part of my ability to implement pomodoro techniques and focus! Thanks for creating it!  I want to enable/disable this from the commandline so that I can then set a hotkey to make it quick and easy.  I've tried to use gnome-shell-extension-tool...but it doesn't work.

$ gnome-shell-extension-tool -e hidetopbar
/usr/lib64/python3.4/site-packages/gi/overrides/__init__.py:313: Warning: The property GSettings:schema is deprecated and shouldn't be used anymore. It will be removed in a future version.
  return super_init_func(self, **new_kwargs)
'hidetopbar' is now enabled.

How can I enable/disable this extension from the commandline?

If it's not currently possible; would this be simple to do?  

Thanks!

**Comment by tuxor1337** [comment]
The command 

    $ gnome-shell-extension-tool -e hidetopbar@mathieu.bidon.ca

works fine for me. According to the shell output you get it should be working for you, as well. Make sure to use the right name (from `~/.local/share/gnome-shell/extensions/`).
