### ISSUE TITLE
Error when running with GNOME 3.18

### ISSUE THREAD

**Issue by tuxor1337** [mlutfy/hidetopbar#79]
Reported via extensions.gnome.org:

What's wrong? Hi, extension does'nt work with 3.18

What have you tried? --

Automatically detected errors:

  Error: No signal &#39;maximize&#39; on object &#39;ShellWM&#39;

Version information:

    Shell version: 3.18.0
    Extension version: 45

**Comment by andrewfader** [comment]
+1

**Comment by andrewfader** [comment]
See https://github.com/micheleg/dash-to-dock/issues/214

**Comment by dffischer** [comment]
I ported the small change @andrewfader mentioned to the intellihide.js of hidetopbar and created pull request #82. For me, doing so fixes the bug.

**Comment by tuxor1337** [comment]
This is not backwards compatible with GNOME 3.16.

**Comment by dffischer** [comment]
This is correct. I think the correct way to implement this would be to register the handler to each of the three signals only if they exist. However, But I do not know how to query the existence of a signal via gnome-shell's javascript interface. If anybody can tell me how to access something like [`g_signal_list_ids`](https://developer.gnome.org/gobject/stable/gobject-Signals.html#g-signal-list-ids) in javascript, I could modify the pull request,

**Comment by gitjod** [comment]
The pull request #82 works for me except notifications appear partly behind the top bar. Also in a Wayland session applications will open by default in the top left corner. If the extension is enabled the header/titlebar of the application appears behind the top bar. These points may be moot now as pull request #82 probably won't be accepted as it is not backwards compatible with 3.16 but I wanted to highlight them anyway.

**Comment by tuxor1337** [comment]
@gitjod The problems with notifications has been issued here: https://github.com/mlutfy/hidetopbar/issues/74

**Comment by ElectricPrism** [comment]
Glad to see 3.18 support being ironed out.

**Comment by dffischer** [comment]
> This is not backwards compatible with GNOME 3.16.

It is now.

**Comment by tuxor1337** [comment]
Nice, thanks!

**Comment by dffischer** [comment]
Thanks for the merge.

**Comment by andrewfader** [comment]
Thanks
