### ISSUE TITLE
Not handling multiple displays.

### ISSUE THREAD

**Issue by Pajn** [mlutfy/hidetopbar#80]
When I boot with an external monitor (the external being primary) plugged in and unplugs it, I can't show the panel by moving the mouse to the top on the internal/laptop screen.

When I boot with no monitor plugged in and plugs it in while running I can show the panel by moving the mouse to the top on the internal/laptop screen but not on the external, however the panel shows up on the external as that is my primary display. Feels pretty weird to show the panel by moving the mouse to the top of the screen where the panel does not appear.

In both cases I can show/hide the panel with the short cut and it shows up on the correct screen (external if plugged in, internal otherwise).

**Comment by tuxor1337** [comment]
I can confirm that the pressure barrier is not reset when the monitor setup is changed (e.g. when the primary monitor changes).

**Comment by Aryetis** [comment]
Just jumping in to share a quick workaround.
You can fix this behavior by restarting the plugin (toggle it off and on).

**Comment by Aryetis** [comment]
In the meantime, you can easily assign a shortcut to reload the "hide top bar" extension.
It makes life easier.

How to do:
1/ Create a "reloadHideTopBar.sh" file
2/ Put this inside the .sh file:
    #/bin/bash
    gnome-shell-extension-tool -d hidetopbar@mathieu.bidon.ca;
    sleep 1;
    gnome-shell-extension-tool -e hidetopbar@mathieu.bidon.ca;
3/ open gnome control center (you can type "gnome-control-center" in a terminal)
4/ go to keyboard settings -> shortcuts -> personal shorcuts -> '+' symbol 
5/ Give a name to your shortcut like "super duper hideTopBar shorcut", and set the command to:
    gnome-terminal -e "path/to/HideTopBar.sh", then click add
6/ set the shortcut by double clicking the "super duper hideTopBar shortcut"
7/ Enjoy

**Comment by Aryetis** [comment]
It didn't fixed the problem for me :/
