### ISSUE TITLE
Failed to commit

### ISSUE THREAD

**Issue by basneve** [mlutfy/hidetopbar#83]
[root@localhost extensions]# git clone https://github.com/mlutfy/hidetopbar.git hidetopbar@mathieu.bidon.ca
Cloning into 'hidetopbar@mathieu.bidon.ca'...
remote: Counting objects: 434, done.
remote: Total 434 (delta 0), reused 0 (delta 0), pack-reused 434
Receiving objects: 100% (434/434), 85.09 KiB | 19.00 KiB/s, done.
Resolving deltas: 100% (226/226), done.
[root@localhost extensions]# cd hidetopbar@mathieu.bidon.ca
[root@localhost hidetopbar@mathieu.bidon.ca]# pwd
/home/bas/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca
[root@localhost hidetopbar@mathieu.bidon.ca]# make schemas
mkdir ./schemas/
glib-compile-schemas --strict --targetdir=./schemas/ .
[root@localhost hidetopbar@mathieu.bidon.ca]# gnome-shell-extension-tool -e hidetopbar@mathieu.bidon.ca
'hidetopbar@mathieu.bidon.ca' is now enabled.

(process:26261): dconf-WARNING **: failed to commit changes to dconf: The connection is closed
[root@localhost hidetopbar@mathieu.bidon.ca]#

**Comment by tuxor1337** [comment]
You shouldn't run this as root.

**Comment by gzliudan** [comment]
[test@master56 hidetopbar@mathieu.bidon.ca]$ gnome-shell-extension-tool -e hidetopbar@mathieu.bidon.ca
'hidetopbar@mathieu.bidon.ca' is now enabled.

(process:4511): dconf-WARNING **: failed to commit changes to dconf: Error spawning command line 'dbus-launch --autolaunch=2a25722518174e678ad5cfcad2655e70 --binary-syntax --close-stderr': Child process exited with code 1
