### ISSUE TITLE
Crashes when opening music in MPV

### ISSUE THREAD

**Issue by oooze81** [mlutfy/hidetopbar#85]
This addon is installed, and I open music from nautilus, which I have set to open in MPV. Often the entire shell will freeze up, and the cursor goes back to the vertical cross shaped one. I have disabled all shell extensions, it only occurs with this installed.

**Comment by tuxor1337** [comment]
I can't reproduce this with GNOME 3.16.4 running on Fedora 22 (x86_64) and mpv 0.9.2 playing an mp3-file. These are the libraries used by mpv in my setup:

    libavutil       54.20.100
    libavcodec      56.26.100
    libavformat     56.25.101
    libswscale      3.1.101
    libavfilter     5.11.102
    libswresample   1.1.100

Which versions are you running? Do you have a multi-monitor setup? Do you have any other windows open besides the nautilus window when you start mpv? Would you please post your hide-top-bar settings?

**Comment by oooze81** [comment]
Apologies, it seems that the issue was actually another extension. Sorry for the incorrect report.
