### ISSUE TITLE
Pressure barrier doesn't work

### ISSUE THREAD

**Issue by latot** [mlutfy/hidetopbar#86]
Hi, here a little problem, when we run gdm from wayland the top hide ar start but it don't show up when the mouse is in top D:

i try get some log but i can't get it D: no info from kernel messages.

Its shows when i press the windows button (when we can see all the windows of gnome-shell)

Thx.

Gentoo 64
Gnome 3.16

**Comment by tuxor1337** [comment]
I can confirm this, but I can't support wayland at the moment because it's not fun debugging GNOME extensions under wayland (e.g. there is no Alt+F2 and `r` and no `gnome-shell --replace`).

**Comment by latot** [comment]
thats not fun D:

**Comment by latot** [comment]
mm, may be this can work:
https://extensions.gnome.org/extension/168/theme-and-shell-reloading/

**Comment by tuxor1337** [comment]
Do you use Wayland on a daily basis? Isn't it a bit too unstable for that?

Thanks for the link, but even if it worked, I would still need a way to look into the debug logs (which is usually by `gnome-shell --replace`).

**Comment by latot** [comment]
Hi, thx. I use gentoo and some times some updates crash the X, so i use in that case wayland waiting for the solution. But actually wayland works very fine, if you don't start playing with some things. The only i try use the las packages of gnome to can use wayland, 3.16 have a lot of bugs, so using 3.18 works fine.

**Comment by tuxor1337** [comment]
Just wanted to drop this her: You _can_ actually follow the logs without restarting, using `journalctl /usr/bin/gnome-shell -f -o cat`.

**Comment by latot** [comment]
:O 
as a note can help run this in a different tty from gnome. (actually i found a lot of crash)

**Comment by latot** [comment]
Thx. :D
