### ISSUE TITLE
Crash on key focusing hidden panel

### ISSUE THREAD

**Issue by 190rr** [mlutfy/hidetopbar#87]
Hi, whenever the top bar is hidden and I try to access it via the 'system controls' menu (Ctrl+Alt+Tab) GNOME Shell will crash.

Running GNOME 3.18.2 on Fedora 23 and latest version of the extension.

**Comment by tuxor1337** [comment]
That is mysterious because I have just done a lot of testing with Ctrl+Alt+Tab in order to work on issue #81 and haven't run into a single crash. I'm also on Fedora 23, but with GNOME 3.18.3 (maybe that's the problem?). Do you have any other extensions running at the same time?

**Comment by tuxor1337** [comment]
We now have a report via extensions.gnome.org with roughly the same content:

> What's wrong?
> Just updated 'Hide Top Bar' to it's latest version via this site and the extension keeps crashing Shell when the top bar is hidden an it is invoked via 'Switch system controls' shortcut.
> 
> 
> What have you tried?
> Ctrl+Alt+Tab --> Top Bar --> BOOM!
> This time I even got a GNOME Shell sad face which forced me to log out and when back all the extensions were disabled.
> 
> 
> Automatically detected errors:
> 
> GNOME Shell Extensions did not detect any errors with this extension.
> 
> Version information:
> 
>     Shell version: 3.18.3
>     Extension version: 48

**Comment by tuxor1337** [comment]
With the latest version, the panel can't be chosen via Ctrl+Alt+Tab when hidden. So this should be gone.
