### ISSUE TITLE
Compatibility with Maximus/PixelSaver

### ISSUE THREAD

**Issue by dffischer** [mlutfy/hidetopbar#88]
When used in combination with [MaximusTwo](https://github.com/wilfm/GnomeExtensionMaximusTwo), [Pixel Saver](https://github.com/deadalnix/pixel-saver) or any fork of the original Maximus extension, selecting tabs in windows touching the upper edge of the screen causes a problem similar to #51: The whole interface becomes unresponsive to any mouse click or hover, despite the pointer can still be moved. Keyboard input is handled still, thus the action key can be used to bring up the overview, which restores mouse reactivity.

How to reproduce:
- Open Firefox, Thunderbird or even gnome-terminal. Seemingly, any application featuring tabs is sufficient to reproduce the bug.
- Maxmize the window.
- Open a new tab so that you now have multiple tabs opened at the top of the window.
- Open any other window, not maxmized, and focus it.
- Target the upper edge of any Firefox tab, where it touches the hidden top bar.
- Click immediately when touching the edge.

It seems to me that the click has to happen when Firefox already recognized the hover event and prepares to show the tooltip for the tab, but the pressure barrier of the top bar has not yet been triggered to move the bar down below the cursor to steal focus from Firefox.

![the bug in action](https://cloud.githubusercontent.com/assets/6497034/11589402/7f30790e-9a88-11e5-810f-35d73318f0d8.png)

**Comment by tuxor1337** [comment]
Even though I think that it's not necessary to open a new issue because this is covered in #51, I leave this as a reference for the bug reports you opened in the other projects. Maybe somebody from there can explain why gnome-shell is acting so strangely without title bars.

**Comment by tuxor1337** [comment]
I can't reproduce this with GNOME 3.36 and the latest versions of Hide Top Bar and Pixel-Saver. Reopen with step-by-step instructions if it still applies to you.
