### ISSUE TITLE
Activities menu stops working

### ISSUE THREAD

**Issue by FMuro** [mlutfy/hidetopbar#91]
Let me say first of all that I LOVE this extension and appreciate very much your work :)

When I start the Gnome shell everything works superb, but after a while using it, the activities menu stops working. The top left corner is insensitive, and even if I click on 'Activities' nothing happens. However if I click on the super key the overview is shown. If I restart the shell (Alt+F2 and then r) everything works again, but after a while the same happens.

I don't know what might be causing this, but it only happens when this extension is on. It usually happens after browsing (firefox, chrome) and checking mails (evolution) with nothing else open.

**Comment by tuxor1337** [comment]
Hi @FMuro, I need more info on your situation:

* Which version of GNOME shell are you using?
* Are there any other GNOME extensions that are running in parallel?
* Can you give a short summary of the Hide Top Bar settings you use?

**Comment by FMuro** [comment]
OMG, how can I have forgotten to provide data? I'm running GNOME Shell 3.18.3. I'm on an up-to-date Fedora 23 without any kind of tweaking, except for the following extensions:

Auto Move Windows
Dash to Dock
Hide Top Bar
Workspaces to Dock

**Comment by FMuro** [comment]
Sorry @tuxor1337 I've been able to reproduce this bug with Hide Top Bar off. I think it's due to another extension. Let's close this.
