### ISSUE TITLE
intellihide doesn't work

### ISSUE THREAD

**Issue by 9Morello** [mlutfy/hidetopbar#92]
Title says it all. Everything else works normally and behaves as expected. However, I can't get the top bar to show automatically when I'm in the desktop or there are no windows obstructing it. I'm using Debian Jessie with GNOME 3.14.1.

**Comment by tuxor1337** [comment]
I'm on 3.18 and I actually don't want to start testing with 3.14 again. Maybe we should drop support for 3.14?

**Comment by coldtobi** [comment]
Which version of hidetopbar are you using? (Debian package or self-installed?)
