### ISSUE TITLE
Top bar does hide when moving window to main screen

### ISSUE THREAD

**Issue by Pierre-Thibault** [mlutfy/hidetopbar#94]
# Preconditions

- Two screens;
- Gnome;
- Intellihide: "Only hide panel when a window takes the place" and "Only when the active window takes the space" are both on;

# Bug

When the top bar is displayed on main screen and a full screen window is moved from a secondary screen to the main screen using Gnome shortcut "move window one screen to the right" then the top bar stay on the main screen.

# Expected behaviour:

The top bar should hide.

# Environment

Gnome 3.14.1

# Notes

I didn't tried with other shortcuts.

**Comment by tuxor1337** [comment]
I don't have two screens at the moment. Can you reproduce this issue with more recent versions of Gnome Shell, like 3.16 or 3.18?

We have another bug with 3.14 (see #92) and maybe it's an option to drop support for <=3.14 if these problems persist.

**Comment by Pierre-Thibault** [comment]
I'll test and I'll come back.

2016-04-04 16:27 GMT-04:00 tuxor1337 <notifications@github.com>:

**Comment by Pierre-Thibault** [comment]
I made a test with Gnome 3.16.4 and the problem does not occur with this version of Gnome.
