### ISSUE TITLE
3.20 support

### ISSUE THREAD

**Issue by nos1609** [mlutfy/hidetopbar#95]
Awaiting for Gnome 3.20 support. Thank You!

**Comment by tuxor1337** [comment]
Have you tried adding 3.20 to the supported versions in `metadata.json`? I'm not on 3.20, so I can't do any testing myself at the moment.

**Comment by nos1609** [comment]
I've tried, but it fails to load...

**Comment by brenoec** [comment]
I've made a pull request that provides 3.20 support:

[https://github.com/mlutfy/hidetopbar/pull/97](url)

I've encountered the same problems as @nos1609 following the steps at README.md file, but I was able to make it work with the tweak tool and a gnome session restart.

**Comment by brenoec** [comment]
Ok, I had the idea to follow the steps on the README.md file and restart gnome session and it worked too. Sorry about that.

I thought that tweak tool internally would do the same as command line, but notify me that a gnome restart as needed. I didn't know about that.

**Comment by tuxor1337** [comment]
Can somebody else confirm that this is working well with Gnome 3.20 ?

**Comment by nos1609** [comment]
@tuxor1337 It's working, hope it'won't crash, as previously. There were some gnome updates, maybe it helped. I'm gonna testing for a day and confirm you it works.

@brenoec the issue was not adding the line to the extension.json, but a crash after a number of window manipulation.

Maybe it's correlated with the use of PixelSaver extension, but this combination worked for me with no issue on 3.18

**Comment by af2005** [comment]
The extensions works fine for me on 3.20. 
I flicked through every setting and it seems all working. Installed via Arch User Repo with modified PKGBUILD and metadata.json (in /usr/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/)

**Comment by tuxor1337** [comment]
Okay, I merged the PR.
